/* PhaseEnum.c generated by valac 0.56.18, the Vala compiler
 * generated from PhaseEnum.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef enum  {
	OLL_MCODER_TASK_PHASE_ENUM_COARSE,
	OLL_MCODER_TASK_PHASE_ENUM_REFINEMENT,
	OLL_MCODER_TASK_PHASE_ENUM_LIST,
	OLL_MCODER_TASK_PHASE_ENUM_REFINE_COMPLETED,
	OLL_MCODER_TASK_PHASE_ENUM_EXECUTION,
	OLL_MCODER_TASK_PHASE_ENUM_POST_EXEC,
	OLL_MCODER_TASK_PHASE_ENUM_NONE,
	OLL_MCODER_TASK_PHASE_ENUM_TASK_LIST_ITERATION,
	OLL_MCODER_TASK_PHASE_ENUM_EXEC_VALIDATE,
	OLL_MCODER_TASK_PHASE_ENUM_TOOLS_RUNNING,
	OLL_MCODER_TASK_PHASE_ENUM_COMPLETED
} OLLMcoderTaskPhaseEnum;

#define OLL_MCODER_TASK_TYPE_PHASE_ENUM (oll_mcoder_task_phase_enum_get_type ())

VALA_EXTERN GType oll_mcoder_task_phase_enum_get_type (void) G_GNUC_CONST ;
VALA_EXTERN OLLMcoderTaskPhaseEnum oll_mcoder_task_phase_enum_from_string (const gchar* id);
VALA_EXTERN gchar* oll_mcoder_task_phase_enum_to_string (OLLMcoderTaskPhaseEnum self);
VALA_EXTERN gchar* oll_mcoder_task_phase_enum_to_human (OLLMcoderTaskPhaseEnum self);

/**
 * Which task-list or executor ''phase'' is active for markdown generation, link validation,
 * and (on restore) transcript replay.
 *
 * ''Prompt / markdown:'' {@link Details.to_markdown}, {@link Step.to_markdown}, and
 * {@link List.to_markdown} take a ''PhaseEnum'' to include the right sections (e.g. tool calls,
 * result summary, references). ''Validation:'' {@link ValidateLink} and {@link ResolveLink}
 * branch on stage so list vs refinement vs executor output get the correct rules.
 *
 * ''Live wire ids:'' the skill runner adds ''agent-stage'' messages whose body is a short id
 * (''task_list_parse'', ''refinement'', ''exec'', …). {@link from_string} maps those strings
 * here; {@link to_string} maps back for stages the live flow emits (others yield '''').
 *
 * == Markdown and planning phases ==
 *
 *  * ''COARSE'' / ''REFINEMENT'' / ''LIST'' — task list and refinement: coarse creation keys,
 *    refined task block, or outstanding list (+ optional executor result summary when
 *    ''exec_done'') for prompts.
 *  * ''REFINE_COMPLETED'' — completed-task markdown for iteration prompts (omits certain
 *    reference sections; see {@link Details.to_markdown}).
 *  * ''EXECUTION'' / ''POST_EXEC'' — executor LLM output vs post-exec synthesis; used in
 *    {@link ResultParser.exec_extract}, {@link ResultParser.exec_post_extract}, and matching
 *    {@link ValidateLink} behavior.
 *
 * == Replay-only and sentinel ==
 *
 *  * ''NONE'' — not a live stage: {@link from_string} default for unknown ids; GTK replay uses
 *    it only until the first ''agent-stage'' applies.
 *  * ''TASK_LIST_ITERATION'' — parsing a revised list ({@link ResultParser.parse_task_list_iteration}).
 *  * ''EXEC_VALIDATE'' — validating executor writes after ''exec''; replay cursor advances here
 *    while consuming ''exec_validate'' / validate ''agent-issues'' rows.
 *
 * @see Details.to_markdown
 * @see List.to_markdown
 * @see ValidateLink
 * @see OLLMcoder.Skill.Runner.on_replay
 */
/**
 * Map a persisted ''agent-stage'' message body to a phase (e.g. ''task_list_parse'' → {@link LIST}).
 *
 * @param id wire content from an ''agent-stage'' row
 * @return matching phase, or {@link NONE} if the id is not recognized
 */
OLLMcoderTaskPhaseEnum
oll_mcoder_task_phase_enum_from_string (const gchar* id)
{
	const gchar* _tmp0_;
	GQuark _tmp2_ = 0U;
	static GQuark _tmp1_label0 = 0;
	static GQuark _tmp1_label1 = 0;
	static GQuark _tmp1_label2 = 0;
	static GQuark _tmp1_label3 = 0;
	static GQuark _tmp1_label4 = 0;
	static GQuark _tmp1_label5 = 0;
	OLLMcoderTaskPhaseEnum result;
	g_return_val_if_fail (id != NULL, 0);
	_tmp0_ = id;
	_tmp2_ = (NULL == _tmp0_) ? 0 : g_quark_from_string (_tmp0_);
	if (_tmp2_ == ((0 != _tmp1_label0) ? _tmp1_label0 : (_tmp1_label0 = g_quark_from_static_string ("task_list_parse")))) {
		switch (0) {
			default:
			{
				result = OLL_MCODER_TASK_PHASE_ENUM_LIST;
				return result;
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label1) ? _tmp1_label1 : (_tmp1_label1 = g_quark_from_static_string ("task_list_iteration")))) {
		switch (0) {
			default:
			{
				result = OLL_MCODER_TASK_PHASE_ENUM_TASK_LIST_ITERATION;
				return result;
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label2) ? _tmp1_label2 : (_tmp1_label2 = g_quark_from_static_string ("refinement")))) {
		switch (0) {
			default:
			{
				result = OLL_MCODER_TASK_PHASE_ENUM_REFINEMENT;
				return result;
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label3) ? _tmp1_label3 : (_tmp1_label3 = g_quark_from_static_string ("exec")))) {
		switch (0) {
			default:
			{
				result = OLL_MCODER_TASK_PHASE_ENUM_EXECUTION;
				return result;
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label4) ? _tmp1_label4 : (_tmp1_label4 = g_quark_from_static_string ("post_exec")))) {
		switch (0) {
			default:
			{
				result = OLL_MCODER_TASK_PHASE_ENUM_POST_EXEC;
				return result;
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label5) ? _tmp1_label5 : (_tmp1_label5 = g_quark_from_static_string ("exec_validate")))) {
		switch (0) {
			default:
			{
				result = OLL_MCODER_TASK_PHASE_ENUM_EXEC_VALIDATE;
				return result;
			}
		}
	} else {
		switch (0) {
			default:
			{
				result = OLL_MCODER_TASK_PHASE_ENUM_NONE;
				return result;
			}
		}
	}
}

/**
 * Stable wire id for ''agent-stage'' messages for phases the live flow emits.
 *
 * Returns '''' for {@link NONE}, {@link COARSE}, {@link REFINE_COMPLETED}, and any value
 * not listed explicitly (those stages are not sent as ''agent-stage'' bodies).
 *
 * @return id string (''exec'', ''exec_validate'', …) or empty string
 */
gchar*
oll_mcoder_task_phase_enum_to_string (OLLMcoderTaskPhaseEnum self)
{
	gchar* result;
	switch (self) {
		case OLL_MCODER_TASK_PHASE_ENUM_NONE:
		{
			gchar* _tmp0_;
			_tmp0_ = g_strdup ("");
			result = _tmp0_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_LIST:
		{
			gchar* _tmp1_;
			_tmp1_ = g_strdup ("task_list_parse");
			result = _tmp1_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_TASK_LIST_ITERATION:
		{
			gchar* _tmp2_;
			_tmp2_ = g_strdup ("task_list_iteration");
			result = _tmp2_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_REFINEMENT:
		{
			gchar* _tmp3_;
			_tmp3_ = g_strdup ("refinement");
			result = _tmp3_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_EXECUTION:
		{
			gchar* _tmp4_;
			_tmp4_ = g_strdup ("exec");
			result = _tmp4_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_POST_EXEC:
		{
			gchar* _tmp5_;
			_tmp5_ = g_strdup ("post_exec");
			result = _tmp5_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_EXEC_VALIDATE:
		{
			gchar* _tmp6_;
			_tmp6_ = g_strdup ("exec_validate");
			result = _tmp6_;
			return result;
		}
		default:
		{
			gchar* _tmp7_;
			_tmp7_ = g_strdup ("");
			result = _tmp7_;
			return result;
		}
	}
}

/**
 * Pango markup for the progress stage column ({@link ProgressItem.status_str}).
 * Gtk: enable markup on the cell/renderer that binds **status-str**.
 */
gchar*
oll_mcoder_task_phase_enum_to_human (OLLMcoderTaskPhaseEnum self)
{
	gchar* result;
	switch (self) {
		case OLL_MCODER_TASK_PHASE_ENUM_NONE:
		case OLL_MCODER_TASK_PHASE_ENUM_REFINE_COMPLETED:
		{
			gchar* _tmp0_;
			_tmp0_ = g_strdup ("");
			result = _tmp0_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_COARSE:
		{
			gchar* _tmp1_;
			_tmp1_ = g_strdup ("<b>Planning</b>");
			result = _tmp1_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_REFINEMENT:
		{
			gchar* _tmp2_;
			_tmp2_ = g_strdup ("<b>Refine</b>");
			result = _tmp2_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_LIST:
		{
			gchar* _tmp3_;
			_tmp3_ = g_strdup ("<b>Creating</b>");
			result = _tmp3_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_TASK_LIST_ITERATION:
		{
			gchar* _tmp4_;
			_tmp4_ = g_strdup ("<b>Updating</b>");
			result = _tmp4_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_EXECUTION:
		case OLL_MCODER_TASK_PHASE_ENUM_TOOLS_RUNNING:
		{
			gchar* _tmp5_;
			_tmp5_ = g_strdup ("<b>Executing</b>");
			result = _tmp5_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_POST_EXEC:
		{
			gchar* _tmp6_;
			_tmp6_ = g_strdup ("<b>Post review</b>");
			result = _tmp6_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_EXEC_VALIDATE:
		{
			gchar* _tmp7_;
			_tmp7_ = g_strdup ("<b>Review</b>");
			result = _tmp7_;
			return result;
		}
		case OLL_MCODER_TASK_PHASE_ENUM_COMPLETED:
		{
			gchar* _tmp8_;
			_tmp8_ = g_strdup ("<span foreground=\"#808080\">✓</span>");
			result = _tmp8_;
			return result;
		}
		default:
		{
			gchar* _tmp9_;
			_tmp9_ = g_strdup ("");
			result = _tmp9_;
			return result;
		}
	}
}

static GType
oll_mcoder_task_phase_enum_get_type_once (void)
{
	static const GEnumValue values[] = {{OLL_MCODER_TASK_PHASE_ENUM_COARSE, "OLL_MCODER_TASK_PHASE_ENUM_COARSE", "coarse"}, {OLL_MCODER_TASK_PHASE_ENUM_REFINEMENT, "OLL_MCODER_TASK_PHASE_ENUM_REFINEMENT", "refinement"}, {OLL_MCODER_TASK_PHASE_ENUM_LIST, "OLL_MCODER_TASK_PHASE_ENUM_LIST", "list"}, {OLL_MCODER_TASK_PHASE_ENUM_REFINE_COMPLETED, "OLL_MCODER_TASK_PHASE_ENUM_REFINE_COMPLETED", "refine-completed"}, {OLL_MCODER_TASK_PHASE_ENUM_EXECUTION, "OLL_MCODER_TASK_PHASE_ENUM_EXECUTION", "execution"}, {OLL_MCODER_TASK_PHASE_ENUM_POST_EXEC, "OLL_MCODER_TASK_PHASE_ENUM_POST_EXEC", "post-exec"}, {OLL_MCODER_TASK_PHASE_ENUM_NONE, "OLL_MCODER_TASK_PHASE_ENUM_NONE", "none"}, {OLL_MCODER_TASK_PHASE_ENUM_TASK_LIST_ITERATION, "OLL_MCODER_TASK_PHASE_ENUM_TASK_LIST_ITERATION", "task-list-iteration"}, {OLL_MCODER_TASK_PHASE_ENUM_EXEC_VALIDATE, "OLL_MCODER_TASK_PHASE_ENUM_EXEC_VALIDATE", "exec-validate"}, {OLL_MCODER_TASK_PHASE_ENUM_TOOLS_RUNNING, "OLL_MCODER_TASK_PHASE_ENUM_TOOLS_RUNNING", "tools-running"}, {OLL_MCODER_TASK_PHASE_ENUM_COMPLETED, "OLL_MCODER_TASK_PHASE_ENUM_COMPLETED", "completed"}, {0, NULL, NULL}};
	GType oll_mcoder_task_phase_enum_type_id;
	oll_mcoder_task_phase_enum_type_id = g_enum_register_static ("OLLMcoderTaskPhaseEnum", values);
	return oll_mcoder_task_phase_enum_type_id;
}

GType
oll_mcoder_task_phase_enum_get_type (void)
{
	static volatile gsize oll_mcoder_task_phase_enum_type_id__once = 0;
	if (g_once_init_enter (&oll_mcoder_task_phase_enum_type_id__once)) {
		GType oll_mcoder_task_phase_enum_type_id;
		oll_mcoder_task_phase_enum_type_id = oll_mcoder_task_phase_enum_get_type_once ();
		g_once_init_leave (&oll_mcoder_task_phase_enum_type_id__once, oll_mcoder_task_phase_enum_type_id);
	}
	return oll_mcoder_task_phase_enum_type_id__once;
}

