/* ProgressItem.c generated by valac 0.56.18, the Vala compiler
 * generated from ProgressItem.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCODER_TASK_TYPE_PROGRESS_ITEM (oll_mcoder_task_progress_item_get_type ())
#define OLL_MCODER_TASK_PROGRESS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCODER_TASK_TYPE_PROGRESS_ITEM, OLLMcoderTaskProgressItem))
#define OLL_MCODER_TASK_IS_PROGRESS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCODER_TASK_TYPE_PROGRESS_ITEM))
#define OLL_MCODER_TASK_PROGRESS_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), OLL_MCODER_TASK_TYPE_PROGRESS_ITEM, OLLMcoderTaskProgressItemIface))

typedef struct _OLLMcoderTaskProgressItem OLLMcoderTaskProgressItem;
typedef struct _OLLMcoderTaskProgressItemIface OLLMcoderTaskProgressItemIface;
typedef enum  {
	OLL_MCODER_TASK_PHASE_ENUM_COARSE,
	OLL_MCODER_TASK_PHASE_ENUM_REFINEMENT,
	OLL_MCODER_TASK_PHASE_ENUM_LIST,
	OLL_MCODER_TASK_PHASE_ENUM_REFINE_COMPLETED,
	OLL_MCODER_TASK_PHASE_ENUM_EXECUTION,
	OLL_MCODER_TASK_PHASE_ENUM_POST_EXEC,
	OLL_MCODER_TASK_PHASE_ENUM_NONE,
	OLL_MCODER_TASK_PHASE_ENUM_TASK_LIST_ITERATION,
	OLL_MCODER_TASK_PHASE_ENUM_EXEC_VALIDATE,
	OLL_MCODER_TASK_PHASE_ENUM_TOOLS_RUNNING,
	OLL_MCODER_TASK_PHASE_ENUM_COMPLETED
} OLLMcoderTaskPhaseEnum;

#define OLL_MCODER_TASK_TYPE_PHASE_ENUM (oll_mcoder_task_phase_enum_get_type ())

struct _OLLMcoderTaskProgressItemIface {
	GTypeInterface parent_iface;
	OLLMcoderTaskPhaseEnum (*get_status) (OLLMcoderTaskProgressItem* self);
	void (*set_status) (OLLMcoderTaskProgressItem* self, OLLMcoderTaskPhaseEnum value);
	gchar* (*get_title) (OLLMcoderTaskProgressItem* self);
	gchar* (*get_status_str) (OLLMcoderTaskProgressItem* self);
	GListModel* (*get_children) (OLLMcoderTaskProgressItem* self);
};

VALA_EXTERN GType oll_mcoder_task_phase_enum_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType oll_mcoder_task_progress_item_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMcoderTaskProgressItem, g_object_unref)
VALA_EXTERN OLLMcoderTaskPhaseEnum oll_mcoder_task_progress_item_get_status (OLLMcoderTaskProgressItem* self);
VALA_EXTERN void oll_mcoder_task_progress_item_set_status (OLLMcoderTaskProgressItem* self,
                                               OLLMcoderTaskPhaseEnum value);
VALA_EXTERN gchar* oll_mcoder_task_progress_item_get_title (OLLMcoderTaskProgressItem* self);
VALA_EXTERN gchar* oll_mcoder_task_progress_item_get_status_str (OLLMcoderTaskProgressItem* self);
VALA_EXTERN GListModel* oll_mcoder_task_progress_item_get_children (OLLMcoderTaskProgressItem* self);
static GType oll_mcoder_task_progress_item_get_type_once (void);

OLLMcoderTaskPhaseEnum
oll_mcoder_task_progress_item_get_status (OLLMcoderTaskProgressItem* self)
{
	OLLMcoderTaskProgressItemIface* _iface_;
	g_return_val_if_fail (self != NULL, 0);
	_iface_ = OLL_MCODER_TASK_PROGRESS_ITEM_GET_INTERFACE (self);
	if (_iface_->get_status) {
		return _iface_->get_status (self);
	}
	return 0;
}

void
oll_mcoder_task_progress_item_set_status (OLLMcoderTaskProgressItem* self,
                                          OLLMcoderTaskPhaseEnum value)
{
	OLLMcoderTaskProgressItemIface* _iface_;
	g_return_if_fail (self != NULL);
	_iface_ = OLL_MCODER_TASK_PROGRESS_ITEM_GET_INTERFACE (self);
	if (_iface_->set_status) {
		_iface_->set_status (self, value);
	}
}

gchar*
oll_mcoder_task_progress_item_get_title (OLLMcoderTaskProgressItem* self)
{
	OLLMcoderTaskProgressItemIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = OLL_MCODER_TASK_PROGRESS_ITEM_GET_INTERFACE (self);
	if (_iface_->get_title) {
		return _iface_->get_title (self);
	}
	return NULL;
}

gchar*
oll_mcoder_task_progress_item_get_status_str (OLLMcoderTaskProgressItem* self)
{
	OLLMcoderTaskProgressItemIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = OLL_MCODER_TASK_PROGRESS_ITEM_GET_INTERFACE (self);
	if (_iface_->get_status_str) {
		return _iface_->get_status_str (self);
	}
	return NULL;
}

GListModel*
oll_mcoder_task_progress_item_get_children (OLLMcoderTaskProgressItem* self)
{
	OLLMcoderTaskProgressItemIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = OLL_MCODER_TASK_PROGRESS_ITEM_GET_INTERFACE (self);
	if (_iface_->get_children) {
		return _iface_->get_children (self);
	}
	return NULL;
}

static void
oll_mcoder_task_progress_item_default_init (OLLMcoderTaskProgressItemIface * iface,
                                            gpointer iface_data)
{
	g_object_interface_install_property (iface, g_param_spec_enum ("status", "status", "status", OLL_MCODER_TASK_TYPE_PHASE_ENUM, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_interface_install_property (iface, g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_interface_install_property (iface, g_param_spec_string ("status-str", "status-str", "status-str", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_interface_install_property (iface, g_param_spec_object ("children", "children", "children", g_list_model_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

/**
 * Row surface for the task progress UI ({@link ProgressList}). **status** is {@link PhaseEnum} (reuse);
 * it **changes** as the row advances. **status_str** is **not** stored — use {@link PhaseEnum.to_human}
 * for the stage column / Gtk bindings (**Pango** markup). The **status** setter emits **notify** for **status_str** only.
 *
 * **children** — {@link GLib.ListModel} whose items are {@link ProgressItem} (**7.14.2**): on {@link Details} use the
 * execution {@link ToolList} (see **7.14.1.3**). On {@link Tool}, an empty {@link GLib.ListStore}.
 */
static GType
oll_mcoder_task_progress_item_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMcoderTaskProgressItemIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mcoder_task_progress_item_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType oll_mcoder_task_progress_item_type_id;
	oll_mcoder_task_progress_item_type_id = g_type_register_static (G_TYPE_INTERFACE, "OLLMcoderTaskProgressItem", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (oll_mcoder_task_progress_item_type_id, G_TYPE_OBJECT);
	return oll_mcoder_task_progress_item_type_id;
}

GType
oll_mcoder_task_progress_item_get_type (void)
{
	static volatile gsize oll_mcoder_task_progress_item_type_id__once = 0;
	if (g_once_init_enter (&oll_mcoder_task_progress_item_type_id__once)) {
		GType oll_mcoder_task_progress_item_type_id;
		oll_mcoder_task_progress_item_type_id = oll_mcoder_task_progress_item_get_type_once ();
		g_once_init_leave (&oll_mcoder_task_progress_item_type_id__once, oll_mcoder_task_progress_item_type_id);
	}
	return oll_mcoder_task_progress_item_type_id__once;
}

