/* ChatCompletionChunk.c generated by valac 0.56.18, the Vala compiler
 * generated from ChatCompletionChunk.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK (oll_mchat_response_chat_completion_chunk_get_type ())
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK, OLLMchatResponseChatCompletionChunk))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK, OLLMchatResponseChatCompletionChunkClass))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_CHUNK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_CHUNK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK, OLLMchatResponseChatCompletionChunkClass))

typedef struct _OLLMchatResponseChatCompletionChunk OLLMchatResponseChatCompletionChunk;
typedef struct _OLLMchatResponseChatCompletionChunkClass OLLMchatResponseChatCompletionChunkClass;
typedef struct _OLLMchatResponseChatCompletionChunkPrivate OLLMchatResponseChatCompletionChunkPrivate;

#define OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE (oll_mchat_response_chat_completion_chunk_choice_get_type ())
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoice))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoiceClass))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_CHUNK_CHOICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_CHUNK_CHOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoiceClass))

typedef struct _OLLMchatResponseChatCompletionChunkChoice OLLMchatResponseChatCompletionChunkChoice;
typedef struct _OLLMchatResponseChatCompletionChunkChoiceClass OLLMchatResponseChatCompletionChunkChoiceClass;
enum  {
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_0_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_ID_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_OBJECT_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_MODEL_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CREATED_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICES_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))

struct _OLLMchatResponseChatCompletionChunk {
	GObject parent_instance;
	OLLMchatResponseChatCompletionChunkPrivate * priv;
};

struct _OLLMchatResponseChatCompletionChunkClass {
	GObjectClass parent_class;
};

struct _OLLMchatResponseChatCompletionChunkPrivate {
	gchar* _id;
	gchar* _object;
	gchar* _model;
	gint64 _created;
	GeeArrayList* _choices;
};

static gint OLLMchatResponseChatCompletionChunk_private_offset;
static gpointer oll_mchat_response_chat_completion_chunk_parent_class = NULL;
static JsonSerializableIface * oll_mchat_response_chat_completion_chunk_json_serializable_parent_iface = NULL;

VALA_EXTERN GType oll_mchat_response_chat_completion_chunk_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseChatCompletionChunk, g_object_unref)
VALA_EXTERN GType oll_mchat_response_chat_completion_chunk_choice_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseChatCompletionChunkChoice, g_object_unref)
static JsonNode* oll_mchat_response_chat_completion_chunk_real_serialize_property (JsonSerializable* base,
                                                                            const gchar* property_name,
                                                                            GValue* value,
                                                                            GParamSpec* pspec);
VALA_EXTERN GeeArrayList* oll_mchat_response_chat_completion_chunk_get_choices (OLLMchatResponseChatCompletionChunk* self);
static gboolean oll_mchat_response_chat_completion_chunk_real_deserialize_property (JsonSerializable* base,
                                                                             const gchar* property_name,
                                                                             GValue* value,
                                                                             GParamSpec* pspec,
                                                                             JsonNode* property_node);
VALA_EXTERN OLLMchatResponseChatCompletionChunk* oll_mchat_response_chat_completion_chunk_new (void);
VALA_EXTERN OLLMchatResponseChatCompletionChunk* oll_mchat_response_chat_completion_chunk_construct (GType object_type);
VALA_EXTERN const gchar* oll_mchat_response_chat_completion_chunk_get_id (OLLMchatResponseChatCompletionChunk* self);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_set_id (OLLMchatResponseChatCompletionChunk* self,
                                                      const gchar* value);
VALA_EXTERN const gchar* oll_mchat_response_chat_completion_chunk_get_object (OLLMchatResponseChatCompletionChunk* self);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_set_object (OLLMchatResponseChatCompletionChunk* self,
                                                          const gchar* value);
VALA_EXTERN const gchar* oll_mchat_response_chat_completion_chunk_get_model (OLLMchatResponseChatCompletionChunk* self);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_set_model (OLLMchatResponseChatCompletionChunk* self,
                                                         const gchar* value);
VALA_EXTERN gint64 oll_mchat_response_chat_completion_chunk_get_created (OLLMchatResponseChatCompletionChunk* self);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_set_created (OLLMchatResponseChatCompletionChunk* self,
                                                           gint64 value);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_set_choices (OLLMchatResponseChatCompletionChunk* self,
                                                           GeeArrayList* value);
static void oll_mchat_response_chat_completion_chunk_finalize (GObject * obj);
static GType oll_mchat_response_chat_completion_chunk_get_type_once (void);
static void _vala_oll_mchat_response_chat_completion_chunk_get_property (GObject * object,
                                                                  guint property_id,
                                                                  GValue * value,
                                                                  GParamSpec * pspec);
static void _vala_oll_mchat_response_chat_completion_chunk_set_property (GObject * object,
                                                                  guint property_id,
                                                                  const GValue * value,
                                                                  GParamSpec * pspec);

static inline gpointer
oll_mchat_response_chat_completion_chunk_get_instance_private (OLLMchatResponseChatCompletionChunk* self)
{
	return G_STRUCT_MEMBER_P (self, OLLMchatResponseChatCompletionChunk_private_offset);
}

static JsonNode*
oll_mchat_response_chat_completion_chunk_real_serialize_property (JsonSerializable* base,
                                                                  const gchar* property_name,
                                                                  GValue* value,
                                                                  GParamSpec* pspec)
{
	OLLMchatResponseChatCompletionChunk * self;
	GeeArrayList* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	JsonArray* arr = NULL;
	JsonArray* _tmp5_;
	JsonNode* node = NULL;
	JsonNode* _tmp17_;
	JsonNode* _tmp18_;
	JsonArray* _tmp19_;
	JsonNode* result;
	self = (OLLMchatResponseChatCompletionChunk*) base;
	g_return_val_if_fail (property_name != NULL, NULL);
	g_return_val_if_fail (value != NULL, NULL);
	g_return_val_if_fail (pspec != NULL, NULL);
	if (g_strcmp0 (property_name, "choices") != 0) {
		GValue _tmp0_;
		JsonNode* _tmp1_;
		_tmp0_ = *value;
		_tmp1_ = json_serializable_default_serialize_property ((JsonSerializable*) self, property_name, &_tmp0_, pspec);
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->priv->_choices;
	_tmp3_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_ == 0) {
		result = NULL;
		return result;
	}
	_tmp5_ = json_array_new ();
	arr = _tmp5_;
	{
		GeeArrayList* _c_list = NULL;
		GeeArrayList* _tmp6_;
		gint _c_size = 0;
		GeeArrayList* _tmp7_;
		gint _tmp8_;
		gint _tmp9_;
		gint _c_index = 0;
		_tmp6_ = self->priv->_choices;
		_c_list = _tmp6_;
		_tmp7_ = _c_list;
		_tmp8_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp7_);
		_tmp9_ = _tmp8_;
		_c_size = _tmp9_;
		_c_index = -1;
		while (TRUE) {
			gint _tmp10_;
			gint _tmp11_;
			OLLMchatResponseChatCompletionChunkChoice* c = NULL;
			GeeArrayList* _tmp12_;
			gpointer _tmp13_;
			JsonArray* _tmp14_;
			OLLMchatResponseChatCompletionChunkChoice* _tmp15_;
			JsonNode* _tmp16_;
			_c_index = _c_index + 1;
			_tmp10_ = _c_index;
			_tmp11_ = _c_size;
			if (!(_tmp10_ < _tmp11_)) {
				break;
			}
			_tmp12_ = _c_list;
			_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _tmp12_, _c_index);
			c = (OLLMchatResponseChatCompletionChunkChoice*) _tmp13_;
			_tmp14_ = arr;
			_tmp15_ = c;
			_tmp16_ = json_gobject_serialize ((GObject*) _tmp15_);
			json_array_add_element (_tmp14_, _tmp16_);
			_g_object_unref0 (c);
		}
	}
	_tmp17_ = json_node_new (JSON_NODE_ARRAY);
	node = _tmp17_;
	_tmp18_ = node;
	_tmp19_ = arr;
	json_node_init_array (_tmp18_, _tmp19_);
	result = node;
	_json_array_unref0 (arr);
	return result;
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static gboolean
oll_mchat_response_chat_completion_chunk_real_deserialize_property (JsonSerializable* base,
                                                                    const gchar* property_name,
                                                                    GValue* value,
                                                                    GParamSpec* pspec,
                                                                    JsonNode* property_node)
{
	OLLMchatResponseChatCompletionChunk * self;
	GValue _vala_value = {0};
	GeeArrayList* _tmp2_;
	JsonArray* array = NULL;
	JsonArray* _tmp3_;
	JsonArray* _tmp4_;
	GValue _tmp15_ = {0};
	GeeArrayList* _tmp16_;
	gboolean result;
	self = (OLLMchatResponseChatCompletionChunk*) base;
	g_return_val_if_fail (property_name != NULL, FALSE);
	g_return_val_if_fail (pspec != NULL, FALSE);
	g_return_val_if_fail (property_node != NULL, FALSE);
	if (g_strcmp0 (property_name, "choices") != 0) {
		GValue _tmp0_ = {0};
		gboolean _tmp1_;
		_tmp1_ = json_serializable_default_deserialize_property ((JsonSerializable*) self, property_name, &_tmp0_, pspec, property_node);
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		_vala_value = _tmp0_;
		result = _tmp1_;
		if (value) {
			*value = _vala_value;
		} else {
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		}
		return result;
	}
	_tmp2_ = self->priv->_choices;
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp2_);
	_tmp3_ = json_node_get_array (property_node);
	_tmp4_ = _json_array_ref0 (_tmp3_);
	array = _tmp4_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp5_ = FALSE;
			_tmp5_ = TRUE;
			while (TRUE) {
				JsonArray* _tmp7_;
				OLLMchatResponseChatCompletionChunkChoice* el = NULL;
				JsonArray* _tmp8_;
				JsonNode* _tmp9_;
				GObject* _tmp10_;
				OLLMchatResponseChatCompletionChunkChoice* _tmp11_;
				OLLMchatResponseChatCompletionChunkChoice* _tmp12_;
				if (!_tmp5_) {
					gint _tmp6_;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp5_ = FALSE;
				_tmp7_ = array;
				if (!(((guint) i) < json_array_get_length (_tmp7_))) {
					break;
				}
				_tmp8_ = array;
				_tmp9_ = json_array_get_element (_tmp8_, (guint) i);
				_tmp10_ = json_gobject_deserialize (OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, _tmp9_);
				_tmp11_ = OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_CHUNK_CHOICE (_tmp10_) ? ((OLLMchatResponseChatCompletionChunkChoice*) _tmp10_) : NULL;
				if (_tmp11_ == NULL) {
					_g_object_unref0 (_tmp10_);
				}
				el = _tmp11_;
				_tmp12_ = el;
				if (_tmp12_ != NULL) {
					GeeArrayList* _tmp13_;
					OLLMchatResponseChatCompletionChunkChoice* _tmp14_;
					_tmp13_ = self->priv->_choices;
					_tmp14_ = el;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp13_, _tmp14_);
				}
				_g_object_unref0 (el);
			}
		}
	}
	g_value_init (&_tmp15_, GEE_TYPE_ARRAY_LIST);
	G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	_vala_value = _tmp15_;
	_tmp16_ = self->priv->_choices;
	g_value_set_object (&_vala_value, (GObject*) _tmp16_);
	result = TRUE;
	_json_array_unref0 (array);
	if (value) {
		*value = _vala_value;
	} else {
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	}
	return result;
}

OLLMchatResponseChatCompletionChunk*
oll_mchat_response_chat_completion_chunk_construct (GType object_type)
{
	OLLMchatResponseChatCompletionChunk * self = NULL;
	self = (OLLMchatResponseChatCompletionChunk*) g_object_new (object_type, NULL);
	return self;
}

OLLMchatResponseChatCompletionChunk*
oll_mchat_response_chat_completion_chunk_new (void)
{
	return oll_mchat_response_chat_completion_chunk_construct (OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK);
}

const gchar*
oll_mchat_response_chat_completion_chunk_get_id (OLLMchatResponseChatCompletionChunk* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_chat_completion_chunk_set_id (OLLMchatResponseChatCompletionChunk* self,
                                                 const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_get_id (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_id);
		self->priv->_id = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_ID_PROPERTY]);
	}
}

const gchar*
oll_mchat_response_chat_completion_chunk_get_object (OLLMchatResponseChatCompletionChunk* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_object;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_chat_completion_chunk_set_object (OLLMchatResponseChatCompletionChunk* self,
                                                     const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_get_object (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_object);
		self->priv->_object = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_OBJECT_PROPERTY]);
	}
}

const gchar*
oll_mchat_response_chat_completion_chunk_get_model (OLLMchatResponseChatCompletionChunk* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_model;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_chat_completion_chunk_set_model (OLLMchatResponseChatCompletionChunk* self,
                                                    const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_get_model (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_model);
		self->priv->_model = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_MODEL_PROPERTY]);
	}
}

gint64
oll_mchat_response_chat_completion_chunk_get_created (OLLMchatResponseChatCompletionChunk* self)
{
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	result = self->priv->_created;
	return result;
}

void
oll_mchat_response_chat_completion_chunk_set_created (OLLMchatResponseChatCompletionChunk* self,
                                                      gint64 value)
{
	gint64 old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_get_created (self);
	if (old_value != value) {
		self->priv->_created = value;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CREATED_PROPERTY]);
	}
}

GeeArrayList*
oll_mchat_response_chat_completion_chunk_get_choices (OLLMchatResponseChatCompletionChunk* self)
{
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_choices;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
oll_mchat_response_chat_completion_chunk_set_choices (OLLMchatResponseChatCompletionChunk* self,
                                                      GeeArrayList* value)
{
	GeeArrayList* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_get_choices (self);
	if (old_value != value) {
		GeeArrayList* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_choices);
		self->priv->_choices = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICES_PROPERTY]);
	}
}

static void
oll_mchat_response_chat_completion_chunk_class_init (OLLMchatResponseChatCompletionChunkClass * klass,
                                                     gpointer klass_data)
{
	oll_mchat_response_chat_completion_chunk_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &OLLMchatResponseChatCompletionChunk_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_oll_mchat_response_chat_completion_chunk_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_oll_mchat_response_chat_completion_chunk_set_property;
	G_OBJECT_CLASS (klass)->finalize = oll_mchat_response_chat_completion_chunk_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_ID_PROPERTY, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_ID_PROPERTY] = g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_OBJECT_PROPERTY, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_OBJECT_PROPERTY] = g_param_spec_string ("object", "object", "object", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_MODEL_PROPERTY, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_MODEL_PROPERTY] = g_param_spec_string ("model", "model", "model", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CREATED_PROPERTY, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CREATED_PROPERTY] = g_param_spec_int64 ("created", "created", "created", G_MININT64, G_MAXINT64, (gint64) 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICES_PROPERTY, oll_mchat_response_chat_completion_chunk_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICES_PROPERTY] = g_param_spec_object ("choices", "choices", "choices", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
oll_mchat_response_chat_completion_chunk_json_serializable_interface_init (JsonSerializableIface * iface,
                                                                           gpointer iface_data)
{
	oll_mchat_response_chat_completion_chunk_json_serializable_parent_iface = g_type_interface_peek_parent (iface);
	iface->serialize_property = (JsonNode* (*) (JsonSerializable*, const gchar*, GValue*, GParamSpec*)) oll_mchat_response_chat_completion_chunk_real_serialize_property;
	iface->deserialize_property = (gboolean (*) (JsonSerializable*, const gchar*, GValue*, GParamSpec*, JsonNode*)) oll_mchat_response_chat_completion_chunk_real_deserialize_property;
}

static void
oll_mchat_response_chat_completion_chunk_instance_init (OLLMchatResponseChatCompletionChunk * self,
                                                        gpointer klass)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GeeArrayList* _tmp3_;
	self->priv = oll_mchat_response_chat_completion_chunk_get_instance_private (self);
	_tmp0_ = g_strdup ("");
	self->priv->_id = _tmp0_;
	_tmp1_ = g_strdup ("");
	self->priv->_object = _tmp1_;
	_tmp2_ = g_strdup ("");
	self->priv->_model = _tmp2_;
	self->priv->_created = (gint64) 0;
	_tmp3_ = gee_array_list_new (OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->priv->_choices = _tmp3_;
}

static void
oll_mchat_response_chat_completion_chunk_finalize (GObject * obj)
{
	OLLMchatResponseChatCompletionChunk * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK, OLLMchatResponseChatCompletionChunk);
	_g_free0 (self->priv->_id);
	_g_free0 (self->priv->_object);
	_g_free0 (self->priv->_model);
	_g_object_unref0 (self->priv->_choices);
	G_OBJECT_CLASS (oll_mchat_response_chat_completion_chunk_parent_class)->finalize (obj);
}

/**
 * One SSE data: line for streaming chat completions.
 * id, object, model, created, choices (array of chunk choice).
 */
static GType
oll_mchat_response_chat_completion_chunk_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatResponseChatCompletionChunkClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_response_chat_completion_chunk_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatResponseChatCompletionChunk), 0, (GInstanceInitFunc) oll_mchat_response_chat_completion_chunk_instance_init, NULL };
	static const GInterfaceInfo json_serializable_info = { (GInterfaceInitFunc) oll_mchat_response_chat_completion_chunk_json_serializable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType oll_mchat_response_chat_completion_chunk_type_id;
	oll_mchat_response_chat_completion_chunk_type_id = g_type_register_static (G_TYPE_OBJECT, "OLLMchatResponseChatCompletionChunk", &g_define_type_info, 0);
	g_type_add_interface_static (oll_mchat_response_chat_completion_chunk_type_id, json_serializable_get_type (), &json_serializable_info);
	OLLMchatResponseChatCompletionChunk_private_offset = g_type_add_instance_private (oll_mchat_response_chat_completion_chunk_type_id, sizeof (OLLMchatResponseChatCompletionChunkPrivate));
	return oll_mchat_response_chat_completion_chunk_type_id;
}

GType
oll_mchat_response_chat_completion_chunk_get_type (void)
{
	static volatile gsize oll_mchat_response_chat_completion_chunk_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_response_chat_completion_chunk_type_id__once)) {
		GType oll_mchat_response_chat_completion_chunk_type_id;
		oll_mchat_response_chat_completion_chunk_type_id = oll_mchat_response_chat_completion_chunk_get_type_once ();
		g_once_init_leave (&oll_mchat_response_chat_completion_chunk_type_id__once, oll_mchat_response_chat_completion_chunk_type_id);
	}
	return oll_mchat_response_chat_completion_chunk_type_id__once;
}

static void
_vala_oll_mchat_response_chat_completion_chunk_get_property (GObject * object,
                                                             guint property_id,
                                                             GValue * value,
                                                             GParamSpec * pspec)
{
	OLLMchatResponseChatCompletionChunk * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK, OLLMchatResponseChatCompletionChunk);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_ID_PROPERTY:
		g_value_set_string (value, oll_mchat_response_chat_completion_chunk_get_id (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_OBJECT_PROPERTY:
		g_value_set_string (value, oll_mchat_response_chat_completion_chunk_get_object (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_MODEL_PROPERTY:
		g_value_set_string (value, oll_mchat_response_chat_completion_chunk_get_model (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CREATED_PROPERTY:
		g_value_set_int64 (value, oll_mchat_response_chat_completion_chunk_get_created (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICES_PROPERTY:
		g_value_set_object (value, oll_mchat_response_chat_completion_chunk_get_choices (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_oll_mchat_response_chat_completion_chunk_set_property (GObject * object,
                                                             guint property_id,
                                                             const GValue * value,
                                                             GParamSpec * pspec)
{
	OLLMchatResponseChatCompletionChunk * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK, OLLMchatResponseChatCompletionChunk);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_ID_PROPERTY:
		oll_mchat_response_chat_completion_chunk_set_id (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_OBJECT_PROPERTY:
		oll_mchat_response_chat_completion_chunk_set_object (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_MODEL_PROPERTY:
		oll_mchat_response_chat_completion_chunk_set_model (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CREATED_PROPERTY:
		oll_mchat_response_chat_completion_chunk_set_created (self, g_value_get_int64 (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICES_PROPERTY:
		oll_mchat_response_chat_completion_chunk_set_choices (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

