/* ChatCompletionChunkChoice.c generated by valac 0.56.18, the Vala compiler
 * generated from ChatCompletionChunkChoice.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE (oll_mchat_response_chat_completion_chunk_choice_get_type ())
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoice))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoiceClass))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_CHUNK_CHOICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_CHUNK_CHOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoiceClass))

typedef struct _OLLMchatResponseChatCompletionChunkChoice OLLMchatResponseChatCompletionChunkChoice;
typedef struct _OLLMchatResponseChatCompletionChunkChoiceClass OLLMchatResponseChatCompletionChunkChoiceClass;
typedef struct _OLLMchatResponseChatCompletionChunkChoicePrivate OLLMchatResponseChatCompletionChunkChoicePrivate;

#define OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA (oll_mchat_response_chat_completion_delta_get_type ())
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDelta))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDeltaClass))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_DELTA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDeltaClass))

typedef struct _OLLMchatResponseChatCompletionDelta OLLMchatResponseChatCompletionDelta;
typedef struct _OLLMchatResponseChatCompletionDeltaClass OLLMchatResponseChatCompletionDeltaClass;
enum  {
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_0_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_INDEX_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_DELTA_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_FINISH_REASON_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_response_chat_completion_chunk_choice_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _OLLMchatResponseChatCompletionChunkChoice {
	GObject parent_instance;
	OLLMchatResponseChatCompletionChunkChoicePrivate * priv;
};

struct _OLLMchatResponseChatCompletionChunkChoiceClass {
	GObjectClass parent_class;
};

struct _OLLMchatResponseChatCompletionChunkChoicePrivate {
	gint _index;
	OLLMchatResponseChatCompletionDelta* _delta;
	gchar* _finish_reason;
};

static gint OLLMchatResponseChatCompletionChunkChoice_private_offset;
static gpointer oll_mchat_response_chat_completion_chunk_choice_parent_class = NULL;
static JsonSerializableIface * oll_mchat_response_chat_completion_chunk_choice_json_serializable_parent_iface = NULL;

VALA_EXTERN GType oll_mchat_response_chat_completion_chunk_choice_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseChatCompletionChunkChoice, g_object_unref)
VALA_EXTERN GType oll_mchat_response_chat_completion_delta_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseChatCompletionDelta, g_object_unref)
VALA_EXTERN OLLMchatResponseChatCompletionDelta* oll_mchat_response_chat_completion_delta_new (void);
VALA_EXTERN OLLMchatResponseChatCompletionDelta* oll_mchat_response_chat_completion_delta_construct (GType object_type);
static JsonNode* oll_mchat_response_chat_completion_chunk_choice_real_serialize_property (JsonSerializable* base,
                                                                                   const gchar* property_name,
                                                                                   GValue* value,
                                                                                   GParamSpec* pspec);
VALA_EXTERN OLLMchatResponseChatCompletionDelta* oll_mchat_response_chat_completion_chunk_choice_get_delta (OLLMchatResponseChatCompletionChunkChoice* self);
static gboolean oll_mchat_response_chat_completion_chunk_choice_real_deserialize_property (JsonSerializable* base,
                                                                                    const gchar* property_name,
                                                                                    GValue* value,
                                                                                    GParamSpec* pspec,
                                                                                    JsonNode* property_node);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_choice_set_delta (OLLMchatResponseChatCompletionChunkChoice* self,
                                                                OLLMchatResponseChatCompletionDelta* value);
VALA_EXTERN OLLMchatResponseChatCompletionChunkChoice* oll_mchat_response_chat_completion_chunk_choice_new (void);
VALA_EXTERN OLLMchatResponseChatCompletionChunkChoice* oll_mchat_response_chat_completion_chunk_choice_construct (GType object_type);
VALA_EXTERN gint oll_mchat_response_chat_completion_chunk_choice_get_index (OLLMchatResponseChatCompletionChunkChoice* self);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_choice_set_index (OLLMchatResponseChatCompletionChunkChoice* self,
                                                                gint value);
VALA_EXTERN const gchar* oll_mchat_response_chat_completion_chunk_choice_get_finish_reason (OLLMchatResponseChatCompletionChunkChoice* self);
VALA_EXTERN void oll_mchat_response_chat_completion_chunk_choice_set_finish_reason (OLLMchatResponseChatCompletionChunkChoice* self,
                                                                        const gchar* value);
static void oll_mchat_response_chat_completion_chunk_choice_finalize (GObject * obj);
static GType oll_mchat_response_chat_completion_chunk_choice_get_type_once (void);
static void _vala_oll_mchat_response_chat_completion_chunk_choice_get_property (GObject * object,
                                                                         guint property_id,
                                                                         GValue * value,
                                                                         GParamSpec * pspec);
static void _vala_oll_mchat_response_chat_completion_chunk_choice_set_property (GObject * object,
                                                                         guint property_id,
                                                                         const GValue * value,
                                                                         GParamSpec * pspec);

static inline gpointer
oll_mchat_response_chat_completion_chunk_choice_get_instance_private (OLLMchatResponseChatCompletionChunkChoice* self)
{
	return G_STRUCT_MEMBER_P (self, OLLMchatResponseChatCompletionChunkChoice_private_offset);
}

static JsonNode*
oll_mchat_response_chat_completion_chunk_choice_real_serialize_property (JsonSerializable* base,
                                                                         const gchar* property_name,
                                                                         GValue* value,
                                                                         GParamSpec* pspec)
{
	OLLMchatResponseChatCompletionChunkChoice * self;
	GValue _tmp2_;
	JsonNode* _tmp3_;
	JsonNode* result;
	self = (OLLMchatResponseChatCompletionChunkChoice*) base;
	g_return_val_if_fail (property_name != NULL, NULL);
	g_return_val_if_fail (value != NULL, NULL);
	g_return_val_if_fail (pspec != NULL, NULL);
	if (g_strcmp0 (property_name, "delta") == 0) {
		OLLMchatResponseChatCompletionDelta* _tmp0_;
		JsonNode* _tmp1_;
		_tmp0_ = self->priv->_delta;
		_tmp1_ = json_gobject_serialize ((GObject*) _tmp0_);
		result = _tmp1_;
		return result;
	}
	_tmp2_ = *value;
	_tmp3_ = json_serializable_default_serialize_property ((JsonSerializable*) self, property_name, &_tmp2_, pspec);
	result = _tmp3_;
	return result;
}

static gboolean
oll_mchat_response_chat_completion_chunk_choice_real_deserialize_property (JsonSerializable* base,
                                                                           const gchar* property_name,
                                                                           GValue* value,
                                                                           GParamSpec* pspec,
                                                                           JsonNode* property_node)
{
	OLLMchatResponseChatCompletionChunkChoice * self;
	GValue _vala_value = {0};
	GObject* _tmp2_;
	OLLMchatResponseChatCompletionDelta* _tmp3_;
	OLLMchatResponseChatCompletionDelta* _tmp4_;
	OLLMchatResponseChatCompletionDelta* _tmp5_;
	GValue _tmp8_ = {0};
	OLLMchatResponseChatCompletionDelta* _tmp9_;
	gboolean result;
	self = (OLLMchatResponseChatCompletionChunkChoice*) base;
	g_return_val_if_fail (property_name != NULL, FALSE);
	g_return_val_if_fail (pspec != NULL, FALSE);
	g_return_val_if_fail (property_node != NULL, FALSE);
	if (g_strcmp0 (property_name, "delta") != 0) {
		GValue _tmp0_ = {0};
		gboolean _tmp1_;
		_tmp1_ = json_serializable_default_deserialize_property ((JsonSerializable*) self, property_name, &_tmp0_, pspec, property_node);
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		_vala_value = _tmp0_;
		result = _tmp1_;
		if (value) {
			*value = _vala_value;
		} else {
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		}
		return result;
	}
	_tmp2_ = json_gobject_deserialize (OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, property_node);
	_tmp3_ = OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_DELTA (_tmp2_) ? ((OLLMchatResponseChatCompletionDelta*) _tmp2_) : NULL;
	if (_tmp3_ == NULL) {
		_g_object_unref0 (_tmp2_);
	}
	_tmp4_ = _tmp3_;
	oll_mchat_response_chat_completion_chunk_choice_set_delta (self, _tmp4_);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = self->priv->_delta;
	if (_tmp5_ == NULL) {
		OLLMchatResponseChatCompletionDelta* _tmp6_;
		OLLMchatResponseChatCompletionDelta* _tmp7_;
		_tmp6_ = oll_mchat_response_chat_completion_delta_new ();
		_tmp7_ = _tmp6_;
		oll_mchat_response_chat_completion_chunk_choice_set_delta (self, _tmp7_);
		_g_object_unref0 (_tmp7_);
	}
	g_value_init (&_tmp8_, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA);
	G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	_vala_value = _tmp8_;
	_tmp9_ = self->priv->_delta;
	g_value_set_object (&_vala_value, (GObject*) _tmp9_);
	result = TRUE;
	if (value) {
		*value = _vala_value;
	} else {
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	}
	return result;
}

OLLMchatResponseChatCompletionChunkChoice*
oll_mchat_response_chat_completion_chunk_choice_construct (GType object_type)
{
	OLLMchatResponseChatCompletionChunkChoice * self = NULL;
	self = (OLLMchatResponseChatCompletionChunkChoice*) g_object_new (object_type, NULL);
	return self;
}

OLLMchatResponseChatCompletionChunkChoice*
oll_mchat_response_chat_completion_chunk_choice_new (void)
{
	return oll_mchat_response_chat_completion_chunk_choice_construct (OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE);
}

gint
oll_mchat_response_chat_completion_chunk_choice_get_index (OLLMchatResponseChatCompletionChunkChoice* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_index;
	return result;
}

void
oll_mchat_response_chat_completion_chunk_choice_set_index (OLLMchatResponseChatCompletionChunkChoice* self,
                                                           gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_choice_get_index (self);
	if (old_value != value) {
		self->priv->_index = value;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_choice_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_INDEX_PROPERTY]);
	}
}

OLLMchatResponseChatCompletionDelta*
oll_mchat_response_chat_completion_chunk_choice_get_delta (OLLMchatResponseChatCompletionChunkChoice* self)
{
	OLLMchatResponseChatCompletionDelta* result;
	OLLMchatResponseChatCompletionDelta* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_delta;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
oll_mchat_response_chat_completion_chunk_choice_set_delta (OLLMchatResponseChatCompletionChunkChoice* self,
                                                           OLLMchatResponseChatCompletionDelta* value)
{
	OLLMchatResponseChatCompletionDelta* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_choice_get_delta (self);
	if (old_value != value) {
		OLLMchatResponseChatCompletionDelta* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_delta);
		self->priv->_delta = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_choice_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_DELTA_PROPERTY]);
	}
}

const gchar*
oll_mchat_response_chat_completion_chunk_choice_get_finish_reason (OLLMchatResponseChatCompletionChunkChoice* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_finish_reason;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_chat_completion_chunk_choice_set_finish_reason (OLLMchatResponseChatCompletionChunkChoice* self,
                                                                   const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_chunk_choice_get_finish_reason (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_finish_reason);
		self->priv->_finish_reason = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_chunk_choice_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_FINISH_REASON_PROPERTY]);
	}
}

static void
oll_mchat_response_chat_completion_chunk_choice_class_init (OLLMchatResponseChatCompletionChunkChoiceClass * klass,
                                                            gpointer klass_data)
{
	oll_mchat_response_chat_completion_chunk_choice_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &OLLMchatResponseChatCompletionChunkChoice_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_oll_mchat_response_chat_completion_chunk_choice_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_oll_mchat_response_chat_completion_chunk_choice_set_property;
	G_OBJECT_CLASS (klass)->finalize = oll_mchat_response_chat_completion_chunk_choice_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_INDEX_PROPERTY, oll_mchat_response_chat_completion_chunk_choice_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_INDEX_PROPERTY] = g_param_spec_int ("index", "index", "index", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_DELTA_PROPERTY, oll_mchat_response_chat_completion_chunk_choice_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_DELTA_PROPERTY] = g_param_spec_object ("delta", "delta", "delta", OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_FINISH_REASON_PROPERTY, oll_mchat_response_chat_completion_chunk_choice_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_FINISH_REASON_PROPERTY] = g_param_spec_string ("finish-reason", "finish-reason", "finish-reason", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
oll_mchat_response_chat_completion_chunk_choice_json_serializable_interface_init (JsonSerializableIface * iface,
                                                                                  gpointer iface_data)
{
	oll_mchat_response_chat_completion_chunk_choice_json_serializable_parent_iface = g_type_interface_peek_parent (iface);
	iface->serialize_property = (JsonNode* (*) (JsonSerializable*, const gchar*, GValue*, GParamSpec*)) oll_mchat_response_chat_completion_chunk_choice_real_serialize_property;
	iface->deserialize_property = (gboolean (*) (JsonSerializable*, const gchar*, GValue*, GParamSpec*, JsonNode*)) oll_mchat_response_chat_completion_chunk_choice_real_deserialize_property;
}

static void
oll_mchat_response_chat_completion_chunk_choice_instance_init (OLLMchatResponseChatCompletionChunkChoice * self,
                                                               gpointer klass)
{
	OLLMchatResponseChatCompletionDelta* _tmp0_;
	gchar* _tmp1_;
	self->priv = oll_mchat_response_chat_completion_chunk_choice_get_instance_private (self);
	self->priv->_index = 0;
	_tmp0_ = oll_mchat_response_chat_completion_delta_new ();
	self->priv->_delta = _tmp0_;
	_tmp1_ = g_strdup ("");
	self->priv->_finish_reason = _tmp1_;
}

static void
oll_mchat_response_chat_completion_chunk_choice_finalize (GObject * obj)
{
	OLLMchatResponseChatCompletionChunkChoice * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoice);
	_g_object_unref0 (self->priv->_delta);
	_g_free0 (self->priv->_finish_reason);
	G_OBJECT_CLASS (oll_mchat_response_chat_completion_chunk_choice_parent_class)->finalize (obj);
}

/**
 * One choice in an SSE chat completion chunk.
 * index, delta, finish_reason.
 */
static GType
oll_mchat_response_chat_completion_chunk_choice_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatResponseChatCompletionChunkChoiceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_response_chat_completion_chunk_choice_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatResponseChatCompletionChunkChoice), 0, (GInstanceInitFunc) oll_mchat_response_chat_completion_chunk_choice_instance_init, NULL };
	static const GInterfaceInfo json_serializable_info = { (GInterfaceInitFunc) oll_mchat_response_chat_completion_chunk_choice_json_serializable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType oll_mchat_response_chat_completion_chunk_choice_type_id;
	oll_mchat_response_chat_completion_chunk_choice_type_id = g_type_register_static (G_TYPE_OBJECT, "OLLMchatResponseChatCompletionChunkChoice", &g_define_type_info, 0);
	g_type_add_interface_static (oll_mchat_response_chat_completion_chunk_choice_type_id, json_serializable_get_type (), &json_serializable_info);
	OLLMchatResponseChatCompletionChunkChoice_private_offset = g_type_add_instance_private (oll_mchat_response_chat_completion_chunk_choice_type_id, sizeof (OLLMchatResponseChatCompletionChunkChoicePrivate));
	return oll_mchat_response_chat_completion_chunk_choice_type_id;
}

GType
oll_mchat_response_chat_completion_chunk_choice_get_type (void)
{
	static volatile gsize oll_mchat_response_chat_completion_chunk_choice_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_response_chat_completion_chunk_choice_type_id__once)) {
		GType oll_mchat_response_chat_completion_chunk_choice_type_id;
		oll_mchat_response_chat_completion_chunk_choice_type_id = oll_mchat_response_chat_completion_chunk_choice_get_type_once ();
		g_once_init_leave (&oll_mchat_response_chat_completion_chunk_choice_type_id__once, oll_mchat_response_chat_completion_chunk_choice_type_id);
	}
	return oll_mchat_response_chat_completion_chunk_choice_type_id__once;
}

static void
_vala_oll_mchat_response_chat_completion_chunk_choice_get_property (GObject * object,
                                                                    guint property_id,
                                                                    GValue * value,
                                                                    GParamSpec * pspec)
{
	OLLMchatResponseChatCompletionChunkChoice * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoice);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_INDEX_PROPERTY:
		g_value_set_int (value, oll_mchat_response_chat_completion_chunk_choice_get_index (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_DELTA_PROPERTY:
		g_value_set_object (value, oll_mchat_response_chat_completion_chunk_choice_get_delta (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_FINISH_REASON_PROPERTY:
		g_value_set_string (value, oll_mchat_response_chat_completion_chunk_choice_get_finish_reason (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_oll_mchat_response_chat_completion_chunk_choice_set_property (GObject * object,
                                                                    guint property_id,
                                                                    const GValue * value,
                                                                    GParamSpec * pspec)
{
	OLLMchatResponseChatCompletionChunkChoice * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_CHUNK_CHOICE, OLLMchatResponseChatCompletionChunkChoice);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_INDEX_PROPERTY:
		oll_mchat_response_chat_completion_chunk_choice_set_index (self, g_value_get_int (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_DELTA_PROPERTY:
		oll_mchat_response_chat_completion_chunk_choice_set_delta (self, g_value_get_object (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_CHUNK_CHOICE_FINISH_REASON_PROPERTY:
		oll_mchat_response_chat_completion_chunk_choice_set_finish_reason (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

