/* ChatCompletionDelta.c generated by valac 0.56.18, the Vala compiler
 * generated from ChatCompletionDelta.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA (oll_mchat_response_chat_completion_delta_get_type ())
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDelta))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDeltaClass))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_DELTA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA))
#define OLL_MCHAT_RESPONSE_IS_CHAT_COMPLETION_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA))
#define OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDeltaClass))

typedef struct _OLLMchatResponseChatCompletionDelta OLLMchatResponseChatCompletionDelta;
typedef struct _OLLMchatResponseChatCompletionDeltaClass OLLMchatResponseChatCompletionDeltaClass;
typedef struct _OLLMchatResponseChatCompletionDeltaPrivate OLLMchatResponseChatCompletionDeltaPrivate;

#define OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA (oll_mchat_response_tool_call_delta_get_type ())
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDelta))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDeltaClass))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDeltaClass))

typedef struct _OLLMchatResponseToolCallDelta OLLMchatResponseToolCallDelta;
typedef struct _OLLMchatResponseToolCallDeltaClass OLLMchatResponseToolCallDeltaClass;
enum  {
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_0_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CONTENT_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_ROLE_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_TOOL_CALLS_PROPERTY,
	OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_response_chat_completion_delta_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))

struct _OLLMchatResponseChatCompletionDelta {
	GObject parent_instance;
	OLLMchatResponseChatCompletionDeltaPrivate * priv;
};

struct _OLLMchatResponseChatCompletionDeltaClass {
	GObjectClass parent_class;
};

struct _OLLMchatResponseChatCompletionDeltaPrivate {
	gchar* _content;
	gchar* _role;
	GeeArrayList* _tool_calls;
};

static gint OLLMchatResponseChatCompletionDelta_private_offset;
static gpointer oll_mchat_response_chat_completion_delta_parent_class = NULL;
static JsonSerializableIface * oll_mchat_response_chat_completion_delta_json_serializable_parent_iface = NULL;

VALA_EXTERN GType oll_mchat_response_chat_completion_delta_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseChatCompletionDelta, g_object_unref)
VALA_EXTERN GType oll_mchat_response_tool_call_delta_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseToolCallDelta, g_object_unref)
static JsonNode* oll_mchat_response_chat_completion_delta_real_serialize_property (JsonSerializable* base,
                                                                            const gchar* property_name,
                                                                            GValue* value,
                                                                            GParamSpec* pspec);
VALA_EXTERN GeeArrayList* oll_mchat_response_chat_completion_delta_get_tool_calls (OLLMchatResponseChatCompletionDelta* self);
static gboolean oll_mchat_response_chat_completion_delta_real_deserialize_property (JsonSerializable* base,
                                                                             const gchar* property_name,
                                                                             GValue* value,
                                                                             GParamSpec* pspec,
                                                                             JsonNode* property_node);
VALA_EXTERN OLLMchatResponseChatCompletionDelta* oll_mchat_response_chat_completion_delta_new (void);
VALA_EXTERN OLLMchatResponseChatCompletionDelta* oll_mchat_response_chat_completion_delta_construct (GType object_type);
VALA_EXTERN const gchar* oll_mchat_response_chat_completion_delta_get_content (OLLMchatResponseChatCompletionDelta* self);
VALA_EXTERN void oll_mchat_response_chat_completion_delta_set_content (OLLMchatResponseChatCompletionDelta* self,
                                                           const gchar* value);
VALA_EXTERN const gchar* oll_mchat_response_chat_completion_delta_get_role (OLLMchatResponseChatCompletionDelta* self);
VALA_EXTERN void oll_mchat_response_chat_completion_delta_set_role (OLLMchatResponseChatCompletionDelta* self,
                                                        const gchar* value);
VALA_EXTERN void oll_mchat_response_chat_completion_delta_set_tool_calls (OLLMchatResponseChatCompletionDelta* self,
                                                              GeeArrayList* value);
static void oll_mchat_response_chat_completion_delta_finalize (GObject * obj);
static GType oll_mchat_response_chat_completion_delta_get_type_once (void);
static void _vala_oll_mchat_response_chat_completion_delta_get_property (GObject * object,
                                                                  guint property_id,
                                                                  GValue * value,
                                                                  GParamSpec * pspec);
static void _vala_oll_mchat_response_chat_completion_delta_set_property (GObject * object,
                                                                  guint property_id,
                                                                  const GValue * value,
                                                                  GParamSpec * pspec);

static inline gpointer
oll_mchat_response_chat_completion_delta_get_instance_private (OLLMchatResponseChatCompletionDelta* self)
{
	return G_STRUCT_MEMBER_P (self, OLLMchatResponseChatCompletionDelta_private_offset);
}

static JsonNode*
oll_mchat_response_chat_completion_delta_real_serialize_property (JsonSerializable* base,
                                                                  const gchar* property_name,
                                                                  GValue* value,
                                                                  GParamSpec* pspec)
{
	OLLMchatResponseChatCompletionDelta * self;
	GeeArrayList* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	JsonArray* arr = NULL;
	JsonArray* _tmp5_;
	JsonNode* node = NULL;
	JsonNode* _tmp17_;
	JsonNode* _tmp18_;
	JsonArray* _tmp19_;
	JsonNode* result;
	self = (OLLMchatResponseChatCompletionDelta*) base;
	g_return_val_if_fail (property_name != NULL, NULL);
	g_return_val_if_fail (value != NULL, NULL);
	g_return_val_if_fail (pspec != NULL, NULL);
	if (g_strcmp0 (property_name, "tool_calls") != 0) {
		GValue _tmp0_;
		JsonNode* _tmp1_;
		_tmp0_ = *value;
		_tmp1_ = json_serializable_default_serialize_property ((JsonSerializable*) self, property_name, &_tmp0_, pspec);
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->priv->_tool_calls;
	_tmp3_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_ == 0) {
		result = NULL;
		return result;
	}
	_tmp5_ = json_array_new ();
	arr = _tmp5_;
	{
		GeeArrayList* _tc_list = NULL;
		GeeArrayList* _tmp6_;
		gint _tc_size = 0;
		GeeArrayList* _tmp7_;
		gint _tmp8_;
		gint _tmp9_;
		gint _tc_index = 0;
		_tmp6_ = self->priv->_tool_calls;
		_tc_list = _tmp6_;
		_tmp7_ = _tc_list;
		_tmp8_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp7_);
		_tmp9_ = _tmp8_;
		_tc_size = _tmp9_;
		_tc_index = -1;
		while (TRUE) {
			gint _tmp10_;
			gint _tmp11_;
			OLLMchatResponseToolCallDelta* tc = NULL;
			GeeArrayList* _tmp12_;
			gpointer _tmp13_;
			JsonArray* _tmp14_;
			OLLMchatResponseToolCallDelta* _tmp15_;
			JsonNode* _tmp16_;
			_tc_index = _tc_index + 1;
			_tmp10_ = _tc_index;
			_tmp11_ = _tc_size;
			if (!(_tmp10_ < _tmp11_)) {
				break;
			}
			_tmp12_ = _tc_list;
			_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _tmp12_, _tc_index);
			tc = (OLLMchatResponseToolCallDelta*) _tmp13_;
			_tmp14_ = arr;
			_tmp15_ = tc;
			_tmp16_ = json_gobject_serialize ((GObject*) _tmp15_);
			json_array_add_element (_tmp14_, _tmp16_);
			_g_object_unref0 (tc);
		}
	}
	_tmp17_ = json_node_new (JSON_NODE_ARRAY);
	node = _tmp17_;
	_tmp18_ = node;
	_tmp19_ = arr;
	json_node_init_array (_tmp18_, _tmp19_);
	result = node;
	_json_array_unref0 (arr);
	return result;
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static gboolean
oll_mchat_response_chat_completion_delta_real_deserialize_property (JsonSerializable* base,
                                                                    const gchar* property_name,
                                                                    GValue* value,
                                                                    GParamSpec* pspec,
                                                                    JsonNode* property_node)
{
	OLLMchatResponseChatCompletionDelta * self;
	GValue _vala_value = {0};
	GeeArrayList* _tmp2_;
	JsonArray* array = NULL;
	JsonArray* _tmp3_;
	JsonArray* _tmp4_;
	GValue _tmp15_ = {0};
	GeeArrayList* _tmp16_;
	gboolean result;
	self = (OLLMchatResponseChatCompletionDelta*) base;
	g_return_val_if_fail (property_name != NULL, FALSE);
	g_return_val_if_fail (pspec != NULL, FALSE);
	g_return_val_if_fail (property_node != NULL, FALSE);
	if (g_strcmp0 (property_name, "tool_calls") != 0) {
		GValue _tmp0_ = {0};
		gboolean _tmp1_;
		_tmp1_ = json_serializable_default_deserialize_property ((JsonSerializable*) self, property_name, &_tmp0_, pspec, property_node);
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		_vala_value = _tmp0_;
		result = _tmp1_;
		if (value) {
			*value = _vala_value;
		} else {
			G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
		}
		return result;
	}
	_tmp2_ = self->priv->_tool_calls;
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp2_);
	_tmp3_ = json_node_get_array (property_node);
	_tmp4_ = _json_array_ref0 (_tmp3_);
	array = _tmp4_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp5_ = FALSE;
			_tmp5_ = TRUE;
			while (TRUE) {
				JsonArray* _tmp7_;
				OLLMchatResponseToolCallDelta* el = NULL;
				JsonArray* _tmp8_;
				JsonNode* _tmp9_;
				GObject* _tmp10_;
				OLLMchatResponseToolCallDelta* _tmp11_;
				OLLMchatResponseToolCallDelta* _tmp12_;
				if (!_tmp5_) {
					gint _tmp6_;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp5_ = FALSE;
				_tmp7_ = array;
				if (!(((guint) i) < json_array_get_length (_tmp7_))) {
					break;
				}
				_tmp8_ = array;
				_tmp9_ = json_array_get_element (_tmp8_, (guint) i);
				_tmp10_ = json_gobject_deserialize (OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, _tmp9_);
				_tmp11_ = OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA (_tmp10_) ? ((OLLMchatResponseToolCallDelta*) _tmp10_) : NULL;
				if (_tmp11_ == NULL) {
					_g_object_unref0 (_tmp10_);
				}
				el = _tmp11_;
				_tmp12_ = el;
				if (_tmp12_ != NULL) {
					GeeArrayList* _tmp13_;
					OLLMchatResponseToolCallDelta* _tmp14_;
					_tmp13_ = self->priv->_tool_calls;
					_tmp14_ = el;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp13_, _tmp14_);
				}
				_g_object_unref0 (el);
			}
		}
	}
	g_value_init (&_tmp15_, GEE_TYPE_ARRAY_LIST);
	G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	_vala_value = _tmp15_;
	_tmp16_ = self->priv->_tool_calls;
	g_value_set_object (&_vala_value, (GObject*) _tmp16_);
	result = TRUE;
	_json_array_unref0 (array);
	if (value) {
		*value = _vala_value;
	} else {
		G_IS_VALUE (&_vala_value) ? (g_value_unset (&_vala_value), NULL) : NULL;
	}
	return result;
}

OLLMchatResponseChatCompletionDelta*
oll_mchat_response_chat_completion_delta_construct (GType object_type)
{
	OLLMchatResponseChatCompletionDelta * self = NULL;
	self = (OLLMchatResponseChatCompletionDelta*) g_object_new (object_type, NULL);
	return self;
}

OLLMchatResponseChatCompletionDelta*
oll_mchat_response_chat_completion_delta_new (void)
{
	return oll_mchat_response_chat_completion_delta_construct (OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA);
}

const gchar*
oll_mchat_response_chat_completion_delta_get_content (OLLMchatResponseChatCompletionDelta* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_content;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_chat_completion_delta_set_content (OLLMchatResponseChatCompletionDelta* self,
                                                      const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_delta_get_content (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_content);
		self->priv->_content = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_delta_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CONTENT_PROPERTY]);
	}
}

const gchar*
oll_mchat_response_chat_completion_delta_get_role (OLLMchatResponseChatCompletionDelta* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_role;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_chat_completion_delta_set_role (OLLMchatResponseChatCompletionDelta* self,
                                                   const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_delta_get_role (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_role);
		self->priv->_role = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_delta_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_ROLE_PROPERTY]);
	}
}

GeeArrayList*
oll_mchat_response_chat_completion_delta_get_tool_calls (OLLMchatResponseChatCompletionDelta* self)
{
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tool_calls;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
oll_mchat_response_chat_completion_delta_set_tool_calls (OLLMchatResponseChatCompletionDelta* self,
                                                         GeeArrayList* value)
{
	GeeArrayList* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_chat_completion_delta_get_tool_calls (self);
	if (old_value != value) {
		GeeArrayList* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_tool_calls);
		self->priv->_tool_calls = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_chat_completion_delta_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_TOOL_CALLS_PROPERTY]);
	}
}

static void
oll_mchat_response_chat_completion_delta_class_init (OLLMchatResponseChatCompletionDeltaClass * klass,
                                                     gpointer klass_data)
{
	oll_mchat_response_chat_completion_delta_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &OLLMchatResponseChatCompletionDelta_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_oll_mchat_response_chat_completion_delta_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_oll_mchat_response_chat_completion_delta_set_property;
	G_OBJECT_CLASS (klass)->finalize = oll_mchat_response_chat_completion_delta_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CONTENT_PROPERTY, oll_mchat_response_chat_completion_delta_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CONTENT_PROPERTY] = g_param_spec_string ("content", "content", "content", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_ROLE_PROPERTY, oll_mchat_response_chat_completion_delta_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_ROLE_PROPERTY] = g_param_spec_string ("role", "role", "role", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_TOOL_CALLS_PROPERTY, oll_mchat_response_chat_completion_delta_properties[OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_TOOL_CALLS_PROPERTY] = g_param_spec_object ("tool-calls", "tool-calls", "tool-calls", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
oll_mchat_response_chat_completion_delta_json_serializable_interface_init (JsonSerializableIface * iface,
                                                                           gpointer iface_data)
{
	oll_mchat_response_chat_completion_delta_json_serializable_parent_iface = g_type_interface_peek_parent (iface);
	iface->serialize_property = (JsonNode* (*) (JsonSerializable*, const gchar*, GValue*, GParamSpec*)) oll_mchat_response_chat_completion_delta_real_serialize_property;
	iface->deserialize_property = (gboolean (*) (JsonSerializable*, const gchar*, GValue*, GParamSpec*, JsonNode*)) oll_mchat_response_chat_completion_delta_real_deserialize_property;
}

static void
oll_mchat_response_chat_completion_delta_instance_init (OLLMchatResponseChatCompletionDelta * self,
                                                        gpointer klass)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	GeeArrayList* _tmp2_;
	self->priv = oll_mchat_response_chat_completion_delta_get_instance_private (self);
	_tmp0_ = g_strdup ("");
	self->priv->_content = _tmp0_;
	_tmp1_ = g_strdup ("");
	self->priv->_role = _tmp1_;
	_tmp2_ = gee_array_list_new (OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	self->priv->_tool_calls = _tmp2_;
}

static void
oll_mchat_response_chat_completion_delta_finalize (GObject * obj)
{
	OLLMchatResponseChatCompletionDelta * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDelta);
	_g_free0 (self->priv->_content);
	_g_free0 (self->priv->_role);
	_g_object_unref0 (self->priv->_tool_calls);
	G_OBJECT_CLASS (oll_mchat_response_chat_completion_delta_parent_class)->finalize (obj);
}

/**
 * Delta object in an SSE chunk choice.
 * Optional content, role, and tool_calls (incremental).
 */
static GType
oll_mchat_response_chat_completion_delta_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatResponseChatCompletionDeltaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_response_chat_completion_delta_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatResponseChatCompletionDelta), 0, (GInstanceInitFunc) oll_mchat_response_chat_completion_delta_instance_init, NULL };
	static const GInterfaceInfo json_serializable_info = { (GInterfaceInitFunc) oll_mchat_response_chat_completion_delta_json_serializable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType oll_mchat_response_chat_completion_delta_type_id;
	oll_mchat_response_chat_completion_delta_type_id = g_type_register_static (G_TYPE_OBJECT, "OLLMchatResponseChatCompletionDelta", &g_define_type_info, 0);
	g_type_add_interface_static (oll_mchat_response_chat_completion_delta_type_id, json_serializable_get_type (), &json_serializable_info);
	OLLMchatResponseChatCompletionDelta_private_offset = g_type_add_instance_private (oll_mchat_response_chat_completion_delta_type_id, sizeof (OLLMchatResponseChatCompletionDeltaPrivate));
	return oll_mchat_response_chat_completion_delta_type_id;
}

GType
oll_mchat_response_chat_completion_delta_get_type (void)
{
	static volatile gsize oll_mchat_response_chat_completion_delta_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_response_chat_completion_delta_type_id__once)) {
		GType oll_mchat_response_chat_completion_delta_type_id;
		oll_mchat_response_chat_completion_delta_type_id = oll_mchat_response_chat_completion_delta_get_type_once ();
		g_once_init_leave (&oll_mchat_response_chat_completion_delta_type_id__once, oll_mchat_response_chat_completion_delta_type_id);
	}
	return oll_mchat_response_chat_completion_delta_type_id__once;
}

static void
_vala_oll_mchat_response_chat_completion_delta_get_property (GObject * object,
                                                             guint property_id,
                                                             GValue * value,
                                                             GParamSpec * pspec)
{
	OLLMchatResponseChatCompletionDelta * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDelta);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CONTENT_PROPERTY:
		g_value_set_string (value, oll_mchat_response_chat_completion_delta_get_content (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_ROLE_PROPERTY:
		g_value_set_string (value, oll_mchat_response_chat_completion_delta_get_role (self));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_TOOL_CALLS_PROPERTY:
		g_value_set_object (value, oll_mchat_response_chat_completion_delta_get_tool_calls (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_oll_mchat_response_chat_completion_delta_set_property (GObject * object,
                                                             guint property_id,
                                                             const GValue * value,
                                                             GParamSpec * pspec)
{
	OLLMchatResponseChatCompletionDelta * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_CHAT_COMPLETION_DELTA, OLLMchatResponseChatCompletionDelta);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_CONTENT_PROPERTY:
		oll_mchat_response_chat_completion_delta_set_content (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_ROLE_PROPERTY:
		oll_mchat_response_chat_completion_delta_set_role (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_RESPONSE_CHAT_COMPLETION_DELTA_TOOL_CALLS_PROPERTY:
		oll_mchat_response_chat_completion_delta_set_tool_calls (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

