/* ToolCallDelta.c generated by valac 0.56.18, the Vala compiler
 * generated from ToolCallDelta.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA (oll_mchat_response_tool_call_delta_get_type ())
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDelta))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDeltaClass))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDeltaClass))

typedef struct _OLLMchatResponseToolCallDelta OLLMchatResponseToolCallDelta;
typedef struct _OLLMchatResponseToolCallDeltaClass OLLMchatResponseToolCallDeltaClass;
typedef struct _OLLMchatResponseToolCallDeltaPrivate OLLMchatResponseToolCallDeltaPrivate;

#define OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION (oll_mchat_response_tool_call_delta_function_get_type ())
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunction))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunctionClass))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunctionClass))

typedef struct _OLLMchatResponseToolCallDeltaFunction OLLMchatResponseToolCallDeltaFunction;
typedef struct _OLLMchatResponseToolCallDeltaFunctionClass OLLMchatResponseToolCallDeltaFunctionClass;
enum  {
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_0_PROPERTY,
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_INDEX_PROPERTY,
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_ID_PROPERTY,
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_PROPERTY,
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_response_tool_call_delta_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _OLLMchatResponseToolCallDelta {
	GObject parent_instance;
	OLLMchatResponseToolCallDeltaPrivate * priv;
};

struct _OLLMchatResponseToolCallDeltaClass {
	GObjectClass parent_class;
};

struct _OLLMchatResponseToolCallDeltaPrivate {
	gint _index;
	gchar* _id;
	OLLMchatResponseToolCallDeltaFunction* _function;
};

static gint OLLMchatResponseToolCallDelta_private_offset;
static gpointer oll_mchat_response_tool_call_delta_parent_class = NULL;
static JsonSerializableIface * oll_mchat_response_tool_call_delta_json_serializable_parent_iface = NULL;

VALA_EXTERN GType oll_mchat_response_tool_call_delta_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseToolCallDelta, g_object_unref)
VALA_EXTERN GType oll_mchat_response_tool_call_delta_function_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseToolCallDeltaFunction, g_object_unref)
VALA_EXTERN OLLMchatResponseToolCallDeltaFunction* oll_mchat_response_tool_call_delta_function_new (void);
VALA_EXTERN OLLMchatResponseToolCallDeltaFunction* oll_mchat_response_tool_call_delta_function_construct (GType object_type);
VALA_EXTERN OLLMchatResponseToolCallDelta* oll_mchat_response_tool_call_delta_new (void);
VALA_EXTERN OLLMchatResponseToolCallDelta* oll_mchat_response_tool_call_delta_construct (GType object_type);
VALA_EXTERN gint oll_mchat_response_tool_call_delta_get_index (OLLMchatResponseToolCallDelta* self);
VALA_EXTERN void oll_mchat_response_tool_call_delta_set_index (OLLMchatResponseToolCallDelta* self,
                                                   gint value);
VALA_EXTERN const gchar* oll_mchat_response_tool_call_delta_get_id (OLLMchatResponseToolCallDelta* self);
VALA_EXTERN void oll_mchat_response_tool_call_delta_set_id (OLLMchatResponseToolCallDelta* self,
                                                const gchar* value);
VALA_EXTERN OLLMchatResponseToolCallDeltaFunction* oll_mchat_response_tool_call_delta_get_function (OLLMchatResponseToolCallDelta* self);
VALA_EXTERN void oll_mchat_response_tool_call_delta_set_function (OLLMchatResponseToolCallDelta* self,
                                                      OLLMchatResponseToolCallDeltaFunction* value);
static void oll_mchat_response_tool_call_delta_finalize (GObject * obj);
static GType oll_mchat_response_tool_call_delta_get_type_once (void);
static void _vala_oll_mchat_response_tool_call_delta_get_property (GObject * object,
                                                            guint property_id,
                                                            GValue * value,
                                                            GParamSpec * pspec);
static void _vala_oll_mchat_response_tool_call_delta_set_property (GObject * object,
                                                            guint property_id,
                                                            const GValue * value,
                                                            GParamSpec * pspec);

static inline gpointer
oll_mchat_response_tool_call_delta_get_instance_private (OLLMchatResponseToolCallDelta* self)
{
	return G_STRUCT_MEMBER_P (self, OLLMchatResponseToolCallDelta_private_offset);
}

OLLMchatResponseToolCallDelta*
oll_mchat_response_tool_call_delta_construct (GType object_type)
{
	OLLMchatResponseToolCallDelta * self = NULL;
	self = (OLLMchatResponseToolCallDelta*) g_object_new (object_type, NULL);
	return self;
}

OLLMchatResponseToolCallDelta*
oll_mchat_response_tool_call_delta_new (void)
{
	return oll_mchat_response_tool_call_delta_construct (OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA);
}

gint
oll_mchat_response_tool_call_delta_get_index (OLLMchatResponseToolCallDelta* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_index;
	return result;
}

void
oll_mchat_response_tool_call_delta_set_index (OLLMchatResponseToolCallDelta* self,
                                              gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_tool_call_delta_get_index (self);
	if (old_value != value) {
		self->priv->_index = value;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_tool_call_delta_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_INDEX_PROPERTY]);
	}
}

const gchar*
oll_mchat_response_tool_call_delta_get_id (OLLMchatResponseToolCallDelta* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_tool_call_delta_set_id (OLLMchatResponseToolCallDelta* self,
                                           const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_tool_call_delta_get_id (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_id);
		self->priv->_id = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_tool_call_delta_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_ID_PROPERTY]);
	}
}

OLLMchatResponseToolCallDeltaFunction*
oll_mchat_response_tool_call_delta_get_function (OLLMchatResponseToolCallDelta* self)
{
	OLLMchatResponseToolCallDeltaFunction* result;
	OLLMchatResponseToolCallDeltaFunction* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_function;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
oll_mchat_response_tool_call_delta_set_function (OLLMchatResponseToolCallDelta* self,
                                                 OLLMchatResponseToolCallDeltaFunction* value)
{
	OLLMchatResponseToolCallDeltaFunction* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_tool_call_delta_get_function (self);
	if (old_value != value) {
		OLLMchatResponseToolCallDeltaFunction* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_function);
		self->priv->_function = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_tool_call_delta_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_PROPERTY]);
	}
}

static void
oll_mchat_response_tool_call_delta_class_init (OLLMchatResponseToolCallDeltaClass * klass,
                                               gpointer klass_data)
{
	oll_mchat_response_tool_call_delta_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &OLLMchatResponseToolCallDelta_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_oll_mchat_response_tool_call_delta_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_oll_mchat_response_tool_call_delta_set_property;
	G_OBJECT_CLASS (klass)->finalize = oll_mchat_response_tool_call_delta_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_INDEX_PROPERTY, oll_mchat_response_tool_call_delta_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_INDEX_PROPERTY] = g_param_spec_int ("index", "index", "index", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_ID_PROPERTY, oll_mchat_response_tool_call_delta_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_ID_PROPERTY] = g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_PROPERTY, oll_mchat_response_tool_call_delta_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_PROPERTY] = g_param_spec_object ("function", "function", "function", OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
oll_mchat_response_tool_call_delta_json_serializable_interface_init (JsonSerializableIface * iface,
                                                                     gpointer iface_data)
{
	oll_mchat_response_tool_call_delta_json_serializable_parent_iface = g_type_interface_peek_parent (iface);
}

static void
oll_mchat_response_tool_call_delta_instance_init (OLLMchatResponseToolCallDelta * self,
                                                  gpointer klass)
{
	gchar* _tmp0_;
	OLLMchatResponseToolCallDeltaFunction* _tmp1_;
	self->priv = oll_mchat_response_tool_call_delta_get_instance_private (self);
	self->priv->_index = 0;
	_tmp0_ = g_strdup ("");
	self->priv->_id = _tmp0_;
	_tmp1_ = oll_mchat_response_tool_call_delta_function_new ();
	self->priv->_function = _tmp1_;
}

static void
oll_mchat_response_tool_call_delta_finalize (GObject * obj)
{
	OLLMchatResponseToolCallDelta * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDelta);
	_g_free0 (self->priv->_id);
	_g_object_unref0 (self->priv->_function);
	G_OBJECT_CLASS (oll_mchat_response_tool_call_delta_parent_class)->finalize (obj);
}

/**
 * One streamed tool call delta in an SSE chunk.
 * index, optional id, optional function (name and arguments string).
 */
static GType
oll_mchat_response_tool_call_delta_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatResponseToolCallDeltaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_response_tool_call_delta_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatResponseToolCallDelta), 0, (GInstanceInitFunc) oll_mchat_response_tool_call_delta_instance_init, NULL };
	static const GInterfaceInfo json_serializable_info = { (GInterfaceInitFunc) oll_mchat_response_tool_call_delta_json_serializable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType oll_mchat_response_tool_call_delta_type_id;
	oll_mchat_response_tool_call_delta_type_id = g_type_register_static (G_TYPE_OBJECT, "OLLMchatResponseToolCallDelta", &g_define_type_info, 0);
	g_type_add_interface_static (oll_mchat_response_tool_call_delta_type_id, json_serializable_get_type (), &json_serializable_info);
	OLLMchatResponseToolCallDelta_private_offset = g_type_add_instance_private (oll_mchat_response_tool_call_delta_type_id, sizeof (OLLMchatResponseToolCallDeltaPrivate));
	return oll_mchat_response_tool_call_delta_type_id;
}

GType
oll_mchat_response_tool_call_delta_get_type (void)
{
	static volatile gsize oll_mchat_response_tool_call_delta_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_response_tool_call_delta_type_id__once)) {
		GType oll_mchat_response_tool_call_delta_type_id;
		oll_mchat_response_tool_call_delta_type_id = oll_mchat_response_tool_call_delta_get_type_once ();
		g_once_init_leave (&oll_mchat_response_tool_call_delta_type_id__once, oll_mchat_response_tool_call_delta_type_id);
	}
	return oll_mchat_response_tool_call_delta_type_id__once;
}

static void
_vala_oll_mchat_response_tool_call_delta_get_property (GObject * object,
                                                       guint property_id,
                                                       GValue * value,
                                                       GParamSpec * pspec)
{
	OLLMchatResponseToolCallDelta * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDelta);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_INDEX_PROPERTY:
		g_value_set_int (value, oll_mchat_response_tool_call_delta_get_index (self));
		break;
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_ID_PROPERTY:
		g_value_set_string (value, oll_mchat_response_tool_call_delta_get_id (self));
		break;
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_PROPERTY:
		g_value_set_object (value, oll_mchat_response_tool_call_delta_get_function (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_oll_mchat_response_tool_call_delta_set_property (GObject * object,
                                                       guint property_id,
                                                       const GValue * value,
                                                       GParamSpec * pspec)
{
	OLLMchatResponseToolCallDelta * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA, OLLMchatResponseToolCallDelta);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_INDEX_PROPERTY:
		oll_mchat_response_tool_call_delta_set_index (self, g_value_get_int (value));
		break;
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_ID_PROPERTY:
		oll_mchat_response_tool_call_delta_set_id (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_PROPERTY:
		oll_mchat_response_tool_call_delta_set_function (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

