/* ToolCallDeltaFunction.c generated by valac 0.56.18, the Vala compiler
 * generated from ToolCallDeltaFunction.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glib-object.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION (oll_mchat_response_tool_call_delta_function_get_type ())
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunction))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunctionClass))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION))
#define OLL_MCHAT_RESPONSE_IS_TOOL_CALL_DELTA_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION))
#define OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunctionClass))

typedef struct _OLLMchatResponseToolCallDeltaFunction OLLMchatResponseToolCallDeltaFunction;
typedef struct _OLLMchatResponseToolCallDeltaFunctionClass OLLMchatResponseToolCallDeltaFunctionClass;
typedef struct _OLLMchatResponseToolCallDeltaFunctionPrivate OLLMchatResponseToolCallDeltaFunctionPrivate;
enum  {
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_0_PROPERTY,
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NAME_PROPERTY,
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_ARGUMENTS_PROPERTY,
	OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_response_tool_call_delta_function_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _OLLMchatResponseToolCallDeltaFunction {
	GObject parent_instance;
	OLLMchatResponseToolCallDeltaFunctionPrivate * priv;
};

struct _OLLMchatResponseToolCallDeltaFunctionClass {
	GObjectClass parent_class;
};

struct _OLLMchatResponseToolCallDeltaFunctionPrivate {
	gchar* _name;
	gchar* _arguments;
};

static gint OLLMchatResponseToolCallDeltaFunction_private_offset;
static gpointer oll_mchat_response_tool_call_delta_function_parent_class = NULL;
static JsonSerializableIface * oll_mchat_response_tool_call_delta_function_json_serializable_parent_iface = NULL;

VALA_EXTERN GType oll_mchat_response_tool_call_delta_function_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatResponseToolCallDeltaFunction, g_object_unref)
VALA_EXTERN OLLMchatResponseToolCallDeltaFunction* oll_mchat_response_tool_call_delta_function_new (void);
VALA_EXTERN OLLMchatResponseToolCallDeltaFunction* oll_mchat_response_tool_call_delta_function_construct (GType object_type);
VALA_EXTERN const gchar* oll_mchat_response_tool_call_delta_function_get_name (OLLMchatResponseToolCallDeltaFunction* self);
VALA_EXTERN void oll_mchat_response_tool_call_delta_function_set_name (OLLMchatResponseToolCallDeltaFunction* self,
                                                           const gchar* value);
VALA_EXTERN const gchar* oll_mchat_response_tool_call_delta_function_get_arguments (OLLMchatResponseToolCallDeltaFunction* self);
VALA_EXTERN void oll_mchat_response_tool_call_delta_function_set_arguments (OLLMchatResponseToolCallDeltaFunction* self,
                                                                const gchar* value);
static void oll_mchat_response_tool_call_delta_function_finalize (GObject * obj);
static GType oll_mchat_response_tool_call_delta_function_get_type_once (void);
static void _vala_oll_mchat_response_tool_call_delta_function_get_property (GObject * object,
                                                                     guint property_id,
                                                                     GValue * value,
                                                                     GParamSpec * pspec);
static void _vala_oll_mchat_response_tool_call_delta_function_set_property (GObject * object,
                                                                     guint property_id,
                                                                     const GValue * value,
                                                                     GParamSpec * pspec);

static inline gpointer
oll_mchat_response_tool_call_delta_function_get_instance_private (OLLMchatResponseToolCallDeltaFunction* self)
{
	return G_STRUCT_MEMBER_P (self, OLLMchatResponseToolCallDeltaFunction_private_offset);
}

OLLMchatResponseToolCallDeltaFunction*
oll_mchat_response_tool_call_delta_function_construct (GType object_type)
{
	OLLMchatResponseToolCallDeltaFunction * self = NULL;
	self = (OLLMchatResponseToolCallDeltaFunction*) g_object_new (object_type, NULL);
	return self;
}

OLLMchatResponseToolCallDeltaFunction*
oll_mchat_response_tool_call_delta_function_new (void)
{
	return oll_mchat_response_tool_call_delta_function_construct (OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION);
}

const gchar*
oll_mchat_response_tool_call_delta_function_get_name (OLLMchatResponseToolCallDeltaFunction* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_tool_call_delta_function_set_name (OLLMchatResponseToolCallDeltaFunction* self,
                                                      const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_tool_call_delta_function_get_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_name);
		self->priv->_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_tool_call_delta_function_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NAME_PROPERTY]);
	}
}

const gchar*
oll_mchat_response_tool_call_delta_function_get_arguments (OLLMchatResponseToolCallDeltaFunction* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_arguments;
	result = _tmp0_;
	return result;
}

void
oll_mchat_response_tool_call_delta_function_set_arguments (OLLMchatResponseToolCallDeltaFunction* self,
                                                           const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = oll_mchat_response_tool_call_delta_function_get_arguments (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_arguments);
		self->priv->_arguments = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, oll_mchat_response_tool_call_delta_function_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_ARGUMENTS_PROPERTY]);
	}
}

static void
oll_mchat_response_tool_call_delta_function_class_init (OLLMchatResponseToolCallDeltaFunctionClass * klass,
                                                        gpointer klass_data)
{
	oll_mchat_response_tool_call_delta_function_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &OLLMchatResponseToolCallDeltaFunction_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_oll_mchat_response_tool_call_delta_function_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_oll_mchat_response_tool_call_delta_function_set_property;
	G_OBJECT_CLASS (klass)->finalize = oll_mchat_response_tool_call_delta_function_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NAME_PROPERTY, oll_mchat_response_tool_call_delta_function_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NAME_PROPERTY] = g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_ARGUMENTS_PROPERTY, oll_mchat_response_tool_call_delta_function_properties[OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_ARGUMENTS_PROPERTY] = g_param_spec_string ("arguments", "arguments", "arguments", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
oll_mchat_response_tool_call_delta_function_json_serializable_interface_init (JsonSerializableIface * iface,
                                                                              gpointer iface_data)
{
	oll_mchat_response_tool_call_delta_function_json_serializable_parent_iface = g_type_interface_peek_parent (iface);
}

static void
oll_mchat_response_tool_call_delta_function_instance_init (OLLMchatResponseToolCallDeltaFunction * self,
                                                           gpointer klass)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	self->priv = oll_mchat_response_tool_call_delta_function_get_instance_private (self);
	_tmp0_ = g_strdup ("");
	self->priv->_name = _tmp0_;
	_tmp1_ = g_strdup ("");
	self->priv->_arguments = _tmp1_;
}

static void
oll_mchat_response_tool_call_delta_function_finalize (GObject * obj)
{
	OLLMchatResponseToolCallDeltaFunction * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunction);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_arguments);
	G_OBJECT_CLASS (oll_mchat_response_tool_call_delta_function_parent_class)->finalize (obj);
}

/**
 * Function part of a streamed tool call delta.
 * In SSE streaming, arguments are sent as incremental string chunks.
 */
static GType
oll_mchat_response_tool_call_delta_function_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatResponseToolCallDeltaFunctionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_response_tool_call_delta_function_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatResponseToolCallDeltaFunction), 0, (GInstanceInitFunc) oll_mchat_response_tool_call_delta_function_instance_init, NULL };
	static const GInterfaceInfo json_serializable_info = { (GInterfaceInitFunc) oll_mchat_response_tool_call_delta_function_json_serializable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType oll_mchat_response_tool_call_delta_function_type_id;
	oll_mchat_response_tool_call_delta_function_type_id = g_type_register_static (G_TYPE_OBJECT, "OLLMchatResponseToolCallDeltaFunction", &g_define_type_info, 0);
	g_type_add_interface_static (oll_mchat_response_tool_call_delta_function_type_id, json_serializable_get_type (), &json_serializable_info);
	OLLMchatResponseToolCallDeltaFunction_private_offset = g_type_add_instance_private (oll_mchat_response_tool_call_delta_function_type_id, sizeof (OLLMchatResponseToolCallDeltaFunctionPrivate));
	return oll_mchat_response_tool_call_delta_function_type_id;
}

GType
oll_mchat_response_tool_call_delta_function_get_type (void)
{
	static volatile gsize oll_mchat_response_tool_call_delta_function_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_response_tool_call_delta_function_type_id__once)) {
		GType oll_mchat_response_tool_call_delta_function_type_id;
		oll_mchat_response_tool_call_delta_function_type_id = oll_mchat_response_tool_call_delta_function_get_type_once ();
		g_once_init_leave (&oll_mchat_response_tool_call_delta_function_type_id__once, oll_mchat_response_tool_call_delta_function_type_id);
	}
	return oll_mchat_response_tool_call_delta_function_type_id__once;
}

static void
_vala_oll_mchat_response_tool_call_delta_function_get_property (GObject * object,
                                                                guint property_id,
                                                                GValue * value,
                                                                GParamSpec * pspec)
{
	OLLMchatResponseToolCallDeltaFunction * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunction);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NAME_PROPERTY:
		g_value_set_string (value, oll_mchat_response_tool_call_delta_function_get_name (self));
		break;
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_ARGUMENTS_PROPERTY:
		g_value_set_string (value, oll_mchat_response_tool_call_delta_function_get_arguments (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_oll_mchat_response_tool_call_delta_function_set_property (GObject * object,
                                                                guint property_id,
                                                                const GValue * value,
                                                                GParamSpec * pspec)
{
	OLLMchatResponseToolCallDeltaFunction * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, OLL_MCHAT_RESPONSE_TYPE_TOOL_CALL_DELTA_FUNCTION, OLLMchatResponseToolCallDeltaFunction);
	switch (property_id) {
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_NAME_PROPERTY:
		oll_mchat_response_tool_call_delta_function_set_name (self, g_value_get_string (value));
		break;
		case OLL_MCHAT_RESPONSE_TOOL_CALL_DELTA_FUNCTION_ARGUMENTS_PROPERTY:
		oll_mchat_response_tool_call_delta_function_set_arguments (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

