/* comma-locals.c generated by valac 0.56.18, the Vala compiler
 * generated from comma-locals.vala, do not modify */

#include <glib-object.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_DEMO (demo_get_type ())
#define DEMO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DEMO, Demo))
#define DEMO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DEMO, DemoClass))
#define IS_DEMO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DEMO))
#define IS_DEMO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DEMO))
#define DEMO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DEMO, DemoClass))

typedef struct _Demo Demo;
typedef struct _DemoClass DemoClass;
typedef struct _DemoPrivate DemoPrivate;
enum  {
	DEMO_0_PROPERTY,
	DEMO_NUM_PROPERTIES
};
static GParamSpec* demo_properties[DEMO_NUM_PROPERTIES];

struct _Demo {
	GObject parent_instance;
	DemoPrivate * priv;
};

struct _DemoClass {
	GObjectClass parent_class;
};

static gpointer demo_parent_class = NULL;

VALA_EXTERN GType demo_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Demo, g_object_unref)
static void demo_go (Demo* self);
VALA_EXTERN Demo* demo_new (void);
VALA_EXTERN Demo* demo_construct (GType object_type);
static GType demo_get_type_once (void);
static void _vala_main (void);

static void
demo_go (Demo* self)
{
	gboolean loading = FALSE;
	gboolean was_systemd = FALSE;
	g_return_if_fail (self != NULL);
	loading = FALSE;
	was_systemd = FALSE;
}

Demo*
demo_construct (GType object_type)
{
	Demo * self = NULL;
	self = (Demo*) g_object_new (object_type, NULL);
	return self;
}

Demo*
demo_new (void)
{
	return demo_construct (TYPE_DEMO);
}

static void
demo_class_init (DemoClass * klass,
                 gpointer klass_data)
{
	demo_parent_class = g_type_class_peek_parent (klass);
}

static void
demo_instance_init (Demo * self,
                    gpointer klass)
{
}

static GType
demo_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DemoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) demo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Demo), 0, (GInstanceInitFunc) demo_instance_init, NULL };
	GType demo_type_id;
	demo_type_id = g_type_register_static (G_TYPE_OBJECT, "Demo", &g_define_type_info, 0);
	return demo_type_id;
}

GType
demo_get_type (void)
{
	static volatile gsize demo_type_id__once = 0;
	if (g_once_init_enter (&demo_type_id__once)) {
		GType demo_type_id;
		demo_type_id = demo_get_type_once ();
		g_once_init_leave (&demo_type_id__once, demo_type_id);
	}
	return demo_type_id__once;
}

static void
_vala_main (void)
{
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

