/* test_checking.c generated by valac 0.56.18, the Vala compiler
 * generated from test_checking.vala, do not modify */

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG (oll_mchat_settings_dialog_checking_connection_dialog_get_type ())
#define OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, OLLMchatSettingsDialogCheckingConnectionDialog))
#define OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, OLLMchatSettingsDialogCheckingConnectionDialogClass))
#define OLL_MCHAT_SETTINGS_DIALOG_IS_CHECKING_CONNECTION_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG))
#define OLL_MCHAT_SETTINGS_DIALOG_IS_CHECKING_CONNECTION_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG))
#define OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, OLLMchatSettingsDialogCheckingConnectionDialogClass))

typedef struct _OLLMchatSettingsDialogCheckingConnectionDialog OLLMchatSettingsDialogCheckingConnectionDialog;
typedef struct _OLLMchatSettingsDialogCheckingConnectionDialogClass OLLMchatSettingsDialogCheckingConnectionDialogClass;
typedef struct _OLLMchatSettingsDialogCheckingConnectionDialogPrivate OLLMchatSettingsDialogCheckingConnectionDialogPrivate;
enum  {
	OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_0_PROPERTY,
	OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_settings_dialog_checking_connection_dialog_properties[OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_NUM_PROPERTIES];

#define OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN (oll_mchat_settings_dialog_test_main_get_type ())
#define OLL_MCHAT_SETTINGS_DIALOG_TEST_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN, OLLMchatSettingsDialogTestMain))
#define OLL_MCHAT_SETTINGS_DIALOG_TEST_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN, OLLMchatSettingsDialogTestMainClass))
#define OLL_MCHAT_SETTINGS_DIALOG_IS_TEST_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN))
#define OLL_MCHAT_SETTINGS_DIALOG_IS_TEST_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN))
#define OLL_MCHAT_SETTINGS_DIALOG_TEST_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN, OLLMchatSettingsDialogTestMainClass))

typedef struct _OLLMchatSettingsDialogTestMain OLLMchatSettingsDialogTestMain;
typedef struct _OLLMchatSettingsDialogTestMainClass OLLMchatSettingsDialogTestMainClass;
typedef struct _OLLMchatSettingsDialogTestMainPrivate OLLMchatSettingsDialogTestMainPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _OLLMchatSettingsDialogParamSpecTestMain OLLMchatSettingsDialogParamSpecTestMain;

struct _OLLMchatSettingsDialogCheckingConnectionDialog {
	AdwDialog parent_instance;
	OLLMchatSettingsDialogCheckingConnectionDialogPrivate * priv;
};

struct _OLLMchatSettingsDialogCheckingConnectionDialogClass {
	AdwDialogClass parent_class;
};

struct _OLLMchatSettingsDialogTestMain {
	GTypeInstance parent_instance;
	volatile int ref_count;
	OLLMchatSettingsDialogTestMainPrivate * priv;
};

struct _OLLMchatSettingsDialogTestMainClass {
	GTypeClass parent_class;
	void (*finalize) (OLLMchatSettingsDialogTestMain *self);
};

struct _OLLMchatSettingsDialogParamSpecTestMain {
	GParamSpec parent_instance;
};

static gpointer oll_mchat_settings_dialog_checking_connection_dialog_parent_class = NULL;
static gpointer oll_mchat_settings_dialog_test_main_parent_class = NULL;

VALA_EXTERN GType oll_mchat_settings_dialog_checking_connection_dialog_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatSettingsDialogCheckingConnectionDialog, g_object_unref)
VALA_EXTERN OLLMchatSettingsDialogCheckingConnectionDialog* oll_mchat_settings_dialog_checking_connection_dialog_new (GtkWindow* parent);
VALA_EXTERN OLLMchatSettingsDialogCheckingConnectionDialog* oll_mchat_settings_dialog_checking_connection_dialog_construct (GType object_type,
                                                                                                                GtkWindow* parent);
static GType oll_mchat_settings_dialog_checking_connection_dialog_get_type_once (void);
VALA_EXTERN gpointer oll_mchat_settings_dialog_test_main_ref (gpointer instance);
VALA_EXTERN void oll_mchat_settings_dialog_test_main_unref (gpointer instance);
VALA_EXTERN GParamSpec* oll_mchat_settings_dialog_param_spec_test_main (const gchar* name,
                                                            const gchar* nick,
                                                            const gchar* blurb,
                                                            GType object_type,
                                                            GParamFlags flags);
VALA_EXTERN void oll_mchat_settings_dialog_value_set_test_main (GValue* value,
                                                    gpointer v_object);
VALA_EXTERN void oll_mchat_settings_dialog_value_take_test_main (GValue* value,
                                                     gpointer v_object);
VALA_EXTERN gpointer oll_mchat_settings_dialog_value_get_test_main (const GValue* value);
VALA_EXTERN GType oll_mchat_settings_dialog_test_main_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatSettingsDialogTestMain, oll_mchat_settings_dialog_test_main_unref)
VALA_EXTERN void oll_mchat_settings_dialog_test_main_test (OLLMchatSettingsDialogTestMain* self);
VALA_EXTERN OLLMchatSettingsDialogTestMain* oll_mchat_settings_dialog_test_main_new (void);
VALA_EXTERN OLLMchatSettingsDialogTestMain* oll_mchat_settings_dialog_test_main_construct (GType object_type);
static void oll_mchat_settings_dialog_test_main_finalize (OLLMchatSettingsDialogTestMain * obj);
static GType oll_mchat_settings_dialog_test_main_get_type_once (void);

OLLMchatSettingsDialogCheckingConnectionDialog*
oll_mchat_settings_dialog_checking_connection_dialog_construct (GType object_type,
                                                                GtkWindow* parent)
{
	OLLMchatSettingsDialogCheckingConnectionDialog * self = NULL;
	self = (OLLMchatSettingsDialogCheckingConnectionDialog*) g_object_new (object_type, "title", "Checking Connection", NULL);
	return self;
}

OLLMchatSettingsDialogCheckingConnectionDialog*
oll_mchat_settings_dialog_checking_connection_dialog_new (GtkWindow* parent)
{
	return oll_mchat_settings_dialog_checking_connection_dialog_construct (OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, parent);
}

static void
oll_mchat_settings_dialog_checking_connection_dialog_class_init (OLLMchatSettingsDialogCheckingConnectionDialogClass * klass,
                                                                 gpointer klass_data)
{
	oll_mchat_settings_dialog_checking_connection_dialog_parent_class = g_type_class_peek_parent (klass);
}

static void
oll_mchat_settings_dialog_checking_connection_dialog_instance_init (OLLMchatSettingsDialogCheckingConnectionDialog * self,
                                                                    gpointer klass)
{
}

 G_GNUC_NO_INLINE static GType
oll_mchat_settings_dialog_checking_connection_dialog_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatSettingsDialogCheckingConnectionDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_settings_dialog_checking_connection_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatSettingsDialogCheckingConnectionDialog), 0, (GInstanceInitFunc) oll_mchat_settings_dialog_checking_connection_dialog_instance_init, NULL };
	GType oll_mchat_settings_dialog_checking_connection_dialog_type_id;
	oll_mchat_settings_dialog_checking_connection_dialog_type_id = g_type_register_static (adw_dialog_get_type (), "OLLMchatSettingsDialogCheckingConnectionDialog", &g_define_type_info, 0);
	return oll_mchat_settings_dialog_checking_connection_dialog_type_id;
}

GType
oll_mchat_settings_dialog_checking_connection_dialog_get_type (void)
{
	static gsize oll_mchat_settings_dialog_checking_connection_dialog_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_settings_dialog_checking_connection_dialog_type_id__once)) {
		GType oll_mchat_settings_dialog_checking_connection_dialog_type_id;
		oll_mchat_settings_dialog_checking_connection_dialog_type_id = oll_mchat_settings_dialog_checking_connection_dialog_get_type_once ();
		g_once_init_leave (&oll_mchat_settings_dialog_checking_connection_dialog_type_id__once, oll_mchat_settings_dialog_checking_connection_dialog_type_id);
	}
	return oll_mchat_settings_dialog_checking_connection_dialog_type_id__once;
}

void
oll_mchat_settings_dialog_test_main_test (OLLMchatSettingsDialogTestMain* self)
{
	OLLMchatSettingsDialogCheckingConnectionDialog* d = NULL;
	OLLMchatSettingsDialogCheckingConnectionDialog* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = oll_mchat_settings_dialog_checking_connection_dialog_new (NULL);
	g_object_ref_sink (_tmp0_);
	d = _tmp0_;
	_g_object_unref0 (d);
}

OLLMchatSettingsDialogTestMain*
oll_mchat_settings_dialog_test_main_construct (GType object_type)
{
	OLLMchatSettingsDialogTestMain* self = NULL;
	self = (OLLMchatSettingsDialogTestMain*) g_type_create_instance (object_type);
	return self;
}

OLLMchatSettingsDialogTestMain*
oll_mchat_settings_dialog_test_main_new (void)
{
	return oll_mchat_settings_dialog_test_main_construct (OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN);
}

static void
oll_mchat_settings_dialog_value_test_main_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
oll_mchat_settings_dialog_value_test_main_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		oll_mchat_settings_dialog_test_main_unref (value->data[0].v_pointer);
	}
}

static void
oll_mchat_settings_dialog_value_test_main_copy_value (const GValue* src_value,
                                                      GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = oll_mchat_settings_dialog_test_main_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
oll_mchat_settings_dialog_value_test_main_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
oll_mchat_settings_dialog_value_test_main_collect_value (GValue* value,
                                                         guint n_collect_values,
                                                         GTypeCValue* collect_values,
                                                         guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		OLLMchatSettingsDialogTestMain * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = oll_mchat_settings_dialog_test_main_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
oll_mchat_settings_dialog_value_test_main_lcopy_value (const GValue* value,
                                                       guint n_collect_values,
                                                       GTypeCValue* collect_values,
                                                       guint collect_flags)
{
	OLLMchatSettingsDialogTestMain ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = oll_mchat_settings_dialog_test_main_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
oll_mchat_settings_dialog_param_spec_test_main (const gchar* name,
                                                const gchar* nick,
                                                const gchar* blurb,
                                                GType object_type,
                                                GParamFlags flags)
{
	OLLMchatSettingsDialogParamSpecTestMain* spec;
	g_return_val_if_fail (g_type_is_a (object_type, OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
oll_mchat_settings_dialog_value_get_test_main (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN), NULL);
	return value->data[0].v_pointer;
}

void
oll_mchat_settings_dialog_value_set_test_main (GValue* value,
                                               gpointer v_object)
{
	OLLMchatSettingsDialogTestMain * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		oll_mchat_settings_dialog_test_main_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		oll_mchat_settings_dialog_test_main_unref (old);
	}
}

void
oll_mchat_settings_dialog_value_take_test_main (GValue* value,
                                                gpointer v_object)
{
	OLLMchatSettingsDialogTestMain * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		oll_mchat_settings_dialog_test_main_unref (old);
	}
}

static void
oll_mchat_settings_dialog_test_main_class_init (OLLMchatSettingsDialogTestMainClass * klass,
                                                gpointer klass_data)
{
	oll_mchat_settings_dialog_test_main_parent_class = g_type_class_peek_parent (klass);
	((OLLMchatSettingsDialogTestMainClass *) klass)->finalize = oll_mchat_settings_dialog_test_main_finalize;
}

static void
oll_mchat_settings_dialog_test_main_instance_init (OLLMchatSettingsDialogTestMain * self,
                                                   gpointer klass)
{
	self->ref_count = 1;
}

static void
oll_mchat_settings_dialog_test_main_finalize (OLLMchatSettingsDialogTestMain * obj)
{
	OLLMchatSettingsDialogTestMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OLL_MCHAT_SETTINGS_DIALOG_TYPE_TEST_MAIN, OLLMchatSettingsDialogTestMain);
	g_signal_handlers_destroy (self);
}

 G_GNUC_NO_INLINE static GType
oll_mchat_settings_dialog_test_main_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { oll_mchat_settings_dialog_value_test_main_init, oll_mchat_settings_dialog_value_test_main_free_value, oll_mchat_settings_dialog_value_test_main_copy_value, oll_mchat_settings_dialog_value_test_main_peek_pointer, "p", oll_mchat_settings_dialog_value_test_main_collect_value, "p", oll_mchat_settings_dialog_value_test_main_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatSettingsDialogTestMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_settings_dialog_test_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatSettingsDialogTestMain), 0, (GInstanceInitFunc) oll_mchat_settings_dialog_test_main_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType oll_mchat_settings_dialog_test_main_type_id;
	oll_mchat_settings_dialog_test_main_type_id = g_type_register_fundamental (g_type_fundamental_next (), "OLLMchatSettingsDialogTestMain", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return oll_mchat_settings_dialog_test_main_type_id;
}

GType
oll_mchat_settings_dialog_test_main_get_type (void)
{
	static gsize oll_mchat_settings_dialog_test_main_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_settings_dialog_test_main_type_id__once)) {
		GType oll_mchat_settings_dialog_test_main_type_id;
		oll_mchat_settings_dialog_test_main_type_id = oll_mchat_settings_dialog_test_main_get_type_once ();
		g_once_init_leave (&oll_mchat_settings_dialog_test_main_type_id__once, oll_mchat_settings_dialog_test_main_type_id);
	}
	return oll_mchat_settings_dialog_test_main_type_id__once;
}

gpointer
oll_mchat_settings_dialog_test_main_ref (gpointer instance)
{
	OLLMchatSettingsDialogTestMain * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
oll_mchat_settings_dialog_test_main_unref (gpointer instance)
{
	OLLMchatSettingsDialogTestMain * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		OLL_MCHAT_SETTINGS_DIALOG_TEST_MAIN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

