/* test_wd.c generated by valac 0.56.18, the Vala compiler
 * generated from test_wd.vala, do not modify */

#include <webkit/webkit.h>
#include <WebKitNavigatorWebDriverActivePolicy.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

static void _vala_main (void);

static void
_vala_main (void)
{
	WebKitSettings* s = NULL;
	WebKitSettings* _tmp0_;
	_tmp0_ = webkit_settings_new ();
	s = _tmp0_;
	webkit_settings_set_navigator_webdriver_active_policy (s, WEBKIT_NAVIGATOR_WEBDRIVER_ACTIVE_POLICY_DISABLED);
	_g_object_unref0 (s);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

