/* CheckingConnectionDialog.c generated by valac 0.56.18, the Vala compiler
 * generated from CheckingConnectionDialog.vala, do not modify */

/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG (oll_mchat_settings_dialog_checking_connection_dialog_get_type ())
#define OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, OLLMchatSettingsDialogCheckingConnectionDialog))
#define OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, OLLMchatSettingsDialogCheckingConnectionDialogClass))
#define OLL_MCHAT_SETTINGS_DIALOG_IS_CHECKING_CONNECTION_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG))
#define OLL_MCHAT_SETTINGS_DIALOG_IS_CHECKING_CONNECTION_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG))
#define OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, OLLMchatSettingsDialogCheckingConnectionDialogClass))

typedef struct _OLLMchatSettingsDialogCheckingConnectionDialog OLLMchatSettingsDialogCheckingConnectionDialog;
typedef struct _OLLMchatSettingsDialogCheckingConnectionDialogClass OLLMchatSettingsDialogCheckingConnectionDialogClass;
typedef struct _OLLMchatSettingsDialogCheckingConnectionDialogPrivate OLLMchatSettingsDialogCheckingConnectionDialogPrivate;
enum  {
	OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_0_PROPERTY,
	OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_NUM_PROPERTIES
};
static GParamSpec* oll_mchat_settings_dialog_checking_connection_dialog_properties[OLL_MCHAT_SETTINGS_DIALOG_CHECKING_CONNECTION_DIALOG_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _OLLMchatSettingsDialogCheckingConnectionDialog {
	AdwDialog parent_instance;
	OLLMchatSettingsDialogCheckingConnectionDialogPrivate * priv;
};

struct _OLLMchatSettingsDialogCheckingConnectionDialogClass {
	AdwDialogClass parent_class;
};

static gpointer oll_mchat_settings_dialog_checking_connection_dialog_parent_class = NULL;

VALA_EXTERN GType oll_mchat_settings_dialog_checking_connection_dialog_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OLLMchatSettingsDialogCheckingConnectionDialog, g_object_unref)
VALA_EXTERN OLLMchatSettingsDialogCheckingConnectionDialog* oll_mchat_settings_dialog_checking_connection_dialog_new (GtkWindow* parent);
VALA_EXTERN OLLMchatSettingsDialogCheckingConnectionDialog* oll_mchat_settings_dialog_checking_connection_dialog_construct (GType object_type,
                                                                                                                GtkWindow* parent);
static GType oll_mchat_settings_dialog_checking_connection_dialog_get_type_once (void);

/**
 * Creates a new CheckingConnectionDialog.
 * 
 * @param parent Parent window to attach the dialog to
 */
OLLMchatSettingsDialogCheckingConnectionDialog*
oll_mchat_settings_dialog_checking_connection_dialog_construct (GType object_type,
                                                                GtkWindow* parent)
{
	OLLMchatSettingsDialogCheckingConnectionDialog * self = NULL;
	GtkBox* box = NULL;
	GtkBox* _tmp0_ = NULL;
	GtkSpinner* spinner = NULL;
	GtkSpinner* _tmp1_ = NULL;
	GtkBox* _tmp2_;
	GtkSpinner* _tmp3_;
	GtkLabel* label = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkBox* _tmp5_;
	GtkLabel* _tmp6_;
	GtkBox* _tmp7_;
	self = (OLLMchatSettingsDialogCheckingConnectionDialog*) g_object_new (object_type, "title", "Checking Connection", NULL);
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 12);
	gtk_widget_set_margin_top ((GtkWidget*) _tmp0_, 24);
	gtk_widget_set_margin_bottom ((GtkWidget*) _tmp0_, 24);
	gtk_widget_set_margin_start ((GtkWidget*) _tmp0_, 24);
	gtk_widget_set_margin_end ((GtkWidget*) _tmp0_, 24);
	gtk_box_set_spacing (_tmp0_, 12);
	g_object_ref_sink (_tmp0_);
	box = _tmp0_;
	_tmp1_ = (GtkSpinner*) gtk_spinner_new ();
	gtk_spinner_set_spinning (_tmp1_, TRUE);
	gtk_widget_set_halign ((GtkWidget*) _tmp1_, GTK_ALIGN_CENTER);
	g_object_set ((GtkWidget*) _tmp1_, "width-request", 48, NULL);
	g_object_set ((GtkWidget*) _tmp1_, "height-request", 48, NULL);
	g_object_ref_sink (_tmp1_);
	spinner = _tmp1_;
	_tmp2_ = box;
	_tmp3_ = spinner;
	gtk_box_append (_tmp2_, (GtkWidget*) _tmp3_);
	_tmp4_ = (GtkLabel*) gtk_label_new ("Verifying connection to server...");
	gtk_widget_set_halign ((GtkWidget*) _tmp4_, GTK_ALIGN_CENTER);
	g_object_ref_sink (_tmp4_);
	label = _tmp4_;
	_tmp5_ = box;
	_tmp6_ = label;
	gtk_box_append (_tmp5_, (GtkWidget*) _tmp6_);
	_tmp7_ = box;
	adw_dialog_set_child ((AdwDialog*) self, (GtkWidget*) _tmp7_);
	if (parent != NULL) {
		adw_dialog_present ((AdwDialog*) self, (GtkWidget*) parent);
	}
	_g_object_unref0 (label);
	_g_object_unref0 (spinner);
	_g_object_unref0 (box);
	return self;
}

OLLMchatSettingsDialogCheckingConnectionDialog*
oll_mchat_settings_dialog_checking_connection_dialog_new (GtkWindow* parent)
{
	return oll_mchat_settings_dialog_checking_connection_dialog_construct (OLL_MCHAT_SETTINGS_DIALOG_TYPE_CHECKING_CONNECTION_DIALOG, parent);
}

static void
oll_mchat_settings_dialog_checking_connection_dialog_class_init (OLLMchatSettingsDialogCheckingConnectionDialogClass * klass,
                                                                 gpointer klass_data)
{
	oll_mchat_settings_dialog_checking_connection_dialog_parent_class = g_type_class_peek_parent (klass);
}

static void
oll_mchat_settings_dialog_checking_connection_dialog_instance_init (OLLMchatSettingsDialogCheckingConnectionDialog * self,
                                                                    gpointer klass)
{
}

/**
 * Dialog that shows a spinner while checking connection.
 * 
 * Used during connection verification to provide user feedback.
 * 
 * @since 1.0
 */
 G_GNUC_NO_INLINE static GType
oll_mchat_settings_dialog_checking_connection_dialog_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (OLLMchatSettingsDialogCheckingConnectionDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) oll_mchat_settings_dialog_checking_connection_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OLLMchatSettingsDialogCheckingConnectionDialog), 0, (GInstanceInitFunc) oll_mchat_settings_dialog_checking_connection_dialog_instance_init, NULL };
	GType oll_mchat_settings_dialog_checking_connection_dialog_type_id;
	oll_mchat_settings_dialog_checking_connection_dialog_type_id = g_type_register_static (adw_dialog_get_type (), "OLLMchatSettingsDialogCheckingConnectionDialog", &g_define_type_info, 0);
	return oll_mchat_settings_dialog_checking_connection_dialog_type_id;
}

GType
oll_mchat_settings_dialog_checking_connection_dialog_get_type (void)
{
	static gsize oll_mchat_settings_dialog_checking_connection_dialog_type_id__once = 0;
	if (g_once_init_enter (&oll_mchat_settings_dialog_checking_connection_dialog_type_id__once)) {
		GType oll_mchat_settings_dialog_checking_connection_dialog_type_id;
		oll_mchat_settings_dialog_checking_connection_dialog_type_id = oll_mchat_settings_dialog_checking_connection_dialog_get_type_once ();
		g_once_init_leave (&oll_mchat_settings_dialog_checking_connection_dialog_type_id__once, oll_mchat_settings_dialog_checking_connection_dialog_type_id);
	}
	return oll_mchat_settings_dialog_checking_connection_dialog_type_id__once;
}

