/*
 * Copyright (C) 2025 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

namespace OLLMapp.SettingsDialog
{
	/**
	 * Tools tab content for settings dialog.
	 * 
	 * Manages tool list and tool-specific configuration.
	 * Uses Adw.PreferencesGroup with Gtk.Box for tool list.
	 * Each tool uses Adw.ExpanderRow for expandable configuration panels.
	 * All tool configuration panels are generated by introspecting the config object.
	 * 
	 * @since 1.0
	 */
	public class ToolsPage : SettingsPage
	{
		/**
		 * Reference to parent SettingsDialog (which has the app object)
		 */
		public MainDialog dialog { get; construct; }
		
		/**
		 * Reference to Client instance to access Client.tools registry.
		 * 
		 * This is used to discover available tools and get tool metadata.
		 * Can be null if tools registry is not available.
		 */
		public OLLMchat.Client? client { get; set; default = null; }
		
		private Adw.PreferencesGroup group;
		private Gtk.Box boxed_list;
		private Gee.HashMap<string, Rows.Tool> tool_rows = new Gee.HashMap<string, Rows.Tool>();
		
		/**
		 * Creates a new ToolsPage.
		 * 
		 * @param dialog Parent SettingsDialog (which has the app object)
		 */
		public ToolsPage(MainDialog dialog)
		{
			Object(
				dialog: dialog,
				page_name: "tools",
				page_title: "Tools",
				orientation: Gtk.Orientation.VERTICAL,
				spacing: 0
			);
			
			// Add proper margins to the page
			this.margin_start = 12;
			this.margin_end = 12;
			this.margin_top = 12;
			this.margin_bottom = 12;
			
			// Create horizontal action bar (set as action_widget for SettingsDialog to manage)
			this.action_widget = new Gtk.Box(Gtk.Orientation.HORIZONTAL, 6) {
				hexpand = true
			};
			
			// Create preferences group
			this.group = new Adw.PreferencesGroup() {
				title = this.page_title
			};
			
			// Create boxed list for tools (using Box instead of ListBox to avoid hover styles)
			this.boxed_list = new Gtk.Box(Gtk.Orientation.VERTICAL, 0);
			this.group.add(this.boxed_list);
			
			// Add preferences group to page
			this.append(this.group);
		}
		
		/**
		 * Loads all tools from Config2.tools and renders their configurations.
		 * 
		 * If Client.tools is available, uses it to get tool metadata (name, description).
		 * Otherwise, uses tool name from Config2.tools keys directly.
		 * Only adds tools that aren't already present in the UI (tools stay once loaded).
		 */
		public void load_tools()
		{
			// Get client with tools from parent window's history_manager
			this.client = (this.dialog.parent as OllmchatWindow).history_manager.base_client;
			
			// Iterate through Config2.tools to discover all configured tools
			foreach (var entry in this.dialog.app.config.tools.entries) {
				// If tool already exists, refresh its config
				if (this.tool_rows.has_key(entry.key)) {
					this.load_configs();
					continue;
				}
				
				// Get tool object from Client.tools if available (for metadata) and create tool row
				var tool_row = new Rows.Tool(
					this.dialog,
					this.client.tools.get(entry.key),
					entry.value,
					entry.key
				);
				
				// Add to list
				this.boxed_list.append(tool_row);
				this.tool_rows.set(entry.key, tool_row);
			}
		}
		
		/**
		 * Loads all configuration values into widgets.
		 * 
		 * Called when the settings dialog is shown to populate widgets with current config values.
		 */
		public void load_configs()
		{
			foreach (var tool_row in this.tool_rows.values) {
				tool_row.load_config();
			}
		}
	}
}

