/*
 * Copyright (C) 2026 Alan Knowles <alan@roojs.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

namespace OLLMapp.SettingsDialog
{
	/**
	 * Tools tab content for settings dialog.
	 * 
	 * Manages tool list and tool-specific configuration.
	 * Uses Adw.PreferencesGroup with Gtk.Box for tool list.
	 * Each tool uses Adw.ExpanderRow for expandable configuration panels.
	 * All tool configuration panels are generated by introspecting the config object.
	 * 
	 * @since 1.0
	 */
	public class ToolsPage : SettingsPage
	{
		/**
		 * Reference to parent SettingsDialog (which has the app object)
		 */
		public MainDialog dialog { get; construct; }
		
		/**
		 * Reference to History Manager to access Manager.tools registry.
		 * 
		 * This is used to discover available tools and get tool metadata.
		 * Can be null if tools registry is not available.
		 */
		public OLLMchat.History.Manager? history_manager { get; set; default = null; }
		
		private Gtk.ScrolledWindow scrolled_window;
		private Adw.PreferencesGroup group;
		private Gtk.Box boxed_list;
		private Gee.HashMap<string, Rows.Tool> tool_rows = new Gee.HashMap<string, Rows.Tool>();
		
		/**
		 * Creates a new ToolsPage.
		 * 
		 * @param dialog Parent SettingsDialog (which has the app object)
		 */
		public ToolsPage(MainDialog dialog)
		{
			Object(
				dialog: dialog,
				page_name: "tools",
				page_title: "Tools",
				orientation: Gtk.Orientation.VERTICAL,
				spacing: 0
			);
			
			// Create horizontal action bar (set as action_widget for SettingsDialog to manage)
			this.action_widget = new Gtk.Box(Gtk.Orientation.HORIZONTAL, 6) {
				hexpand = true
			};
			
			// Create preferences group (no title; tab already shows "Tools")
			this.group = new Adw.PreferencesGroup();
			
			// Create boxed list for tools (using Box instead of ListBox to avoid hover styles)
			this.boxed_list = new Gtk.Box(Gtk.Orientation.VERTICAL, 0);
			this.group.add(this.boxed_list);
			
			// Page has its own ScrolledWindow (no shared outer scroll)
			this.scrolled_window = new Gtk.ScrolledWindow() {
				vexpand = true,
				hexpand = true
			};
			this.scrolled_window.set_child(this.group);
			this.scrolled_window.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC);
			this.append(this.scrolled_window);
		}
		
		/**
		 * Loads all tools from Config2.tools and renders their configurations.
		 * 
		 * If Manager.tools is available, uses it to get tool metadata (name, description).
		 * Otherwise, uses tool name from Config2.tools keys directly.
		 * Only adds tools that aren't already present in the UI (tools stay once loaded).
		 */
		public void load_tools()
		{
			// Get history_manager with tools from parent window
			this.history_manager = (this.dialog.parent as OllmchatWindow).history_manager;
			
			// Iterate through Config2.tools to discover all configured tools
			foreach (var entry in this.dialog.app.config.tools.entries) {
				// If tool already exists, refresh its config
				if (this.tool_rows.has_key(entry.key)) {
					this.load_configs();
					continue;
				}
				
				// Get tool object from Manager.tools if available (for metadata) and create tool row
				var tool_row = new Rows.Tool(
					this.dialog,
					this.history_manager != null && this.history_manager.tools.has_key(entry.key) ? this.history_manager.tools.get(entry.key) : null,
					entry.value,
					entry.key
				);
				
				// Add to list
				this.boxed_list.append(tool_row);
				this.tool_rows.set(entry.key, tool_row);
			}
		}
		
		/**
		 * Loads all configuration values into widgets.
		 * 
		 * Called when the settings dialog is shown to populate widgets with current config values.
		 */
		public void load_configs()
		{
			foreach (var tool_row in this.tool_rows.values) {
				tool_row.load_config();
			}
		}
	}
}

