[Icon Theme]
Name=Adwaita
Comment=OLLMchat Android curated subset
Example=folder
Inherits=hicolor
Hidden=true

Directories=symbolic/actions,symbolic/categories,symbolic/status,scalable/apps,

[symbolic/actions]
Context=Actions
Size=16
Type=Scalable
MinSize=1
MaxSize=512

[symbolic/categories]
Context=Categories
Size=16
Type=Scalable
MinSize=1
MaxSize=512

[symbolic/status]
Context=Status
Size=16
Type=Scalable
MinSize=1
MaxSize=512

[scalable/apps]
Context=Applications
Size=128
Type=Scalable
MinSize=1
MaxSize=512
